#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zephyr.Web.Sys.Areas.Sys.Views.Generator
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Sys/Views/Generator/TemplateEditController.cshtml")]
    public partial class TemplateEditController : System.Web.Mvc.WebViewPage<dynamic>
    {
        public TemplateEditController()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
  
    var area = Model.Data["area"];
    var condtions = Model.Data["conditions"];
    var columns = Model.Data["columns"];
    var controller = Model.Data["controller"];
    var count1 = condtions.Count;
    var count2 = columns.Count;
    var PrimaryKey = Model.PrimaryKeys[0];
    var tabs = Model.Data["tabs"];
    var mainTable = Model.Data["table"];
    var count3 = tabs[0].columns.Count;
    
    //取得明细grid的rowId字段
    for (var i = 0; i < tabs.Count; i++)
    {
        if (tabs[i].type == "grid"){
            tabs[i].rowId = tabs[i].relationship;
            foreach(var item in tabs[i].primaryKeys)
            {
                if (item!=tabs[i].relationship){
                    tabs[i].rowId = item;
                    break; 
                }
            }
        }
    }

            
            #line default
            #line hidden
WriteLiteral(@"
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Net.Http;
using System.Web.Http;
using System.Web.Mvc;
using Newtonsoft.Json.Linq;
using Zephyr.Core;
using Zephyr.Web.Mvc;
using Zephyr.Web.Sys.Models;
using Zephyr.Web.");

            
            #line 38 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
             Write(area);

            
            #line default
            #line hidden
WriteLiteral(".Models;\r\n\r\nnamespace Zephyr.Web.");

            
            #line 40 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                 Write(area);

            
            #line default
            #line hidden
WriteLiteral(".Controllers\r\n{\r\n    public class ");

            
            #line 42 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
             Write(controller);

            
            #line default
            #line hidden
WriteLiteral("Controller : Controller\r\n    {\r\n        public ActionResult Edit(string id = \"\")\r" +
"\n        {\r\n\r\n            var model = new\r\n            {\r\n                urls =" +
" new {\r\n                    getdata = \"/api/");

            
            #line 50 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                                Write(area);

            
            #line default
            #line hidden
WriteLiteral("/");

            
            #line 50 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                                       Write(controller);

            
            #line default
            #line hidden
WriteLiteral("/GetPageData/\",        //获取主表数据及数据滚动数据api\r\n                    edit = \"/api/");

            
            #line 51 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                             Write(area);

            
            #line default
            #line hidden
WriteLiteral("/");

            
            #line 51 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                                    Write(controller);

            
            #line default
            #line hidden
WriteLiteral("/edit/\",                      //数据保存api\r\n                    audit = \"/api/");

            
            #line 52 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                              Write(area);

            
            #line default
            #line hidden
WriteLiteral("/");

            
            #line 52 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                                     Write(controller);

            
            #line default
            #line hidden
WriteLiteral("/audit/\",                    //审核api\r\n                    newkey = \"/api/");

            
            #line 53 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                               Write(area);

            
            #line default
            #line hidden
WriteLiteral("/");

            
            #line 53 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                                      Write(controller);

            
            #line default
            #line hidden
WriteLiteral(@"/GetNewRowId/""            //获取新的明细数据的主键(日语叫采番)
                },
                resx = new {
                    rejected = ""已撤消修改！"",
                    editSuccess = ""保存成功！"",
                    auditPassed =""单据已通过审核！"",
                    auditReject = ""单据已取消审核！""
                },
                dataSource = new{
                    pageData=new ");

            
            #line 62 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                             Write(controller);

            
            #line default
            #line hidden
WriteLiteral("ApiController().GetPageData(id)\r\n                    //payKinds = codeService.Get" +
"ValueTextListByType(\"PayType\")\r\n                },\r\n                form = new{\r" +
"\n                    defaults = new ");

            
            #line 66 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                               Write(mainTable);

            
            #line default
            #line hidden
WriteLiteral("().Extend(new {  ");

            
            #line 66 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                                                                 for (var i = 0; i < count1; i++){
            
            #line default
            #line hidden
            
            #line 66 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                                                                                                    Write(condtions[i].field);

            
            #line default
            #line hidden
WriteLiteral(" = \"\"");

            
            #line 66 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                                                                                                                                         if (i < count1 - 1) {
            
            #line default
            #line hidden
            
            #line 66 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                                                                                                                                                          Write(",");

            
            #line default
            #line hidden
            
            #line 66 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                                                                                                                                                                    }}
            
            #line default
            #line hidden
WriteLiteral("}),\r\n                    primaryKeys = new string[]{\"");

            
            #line 67 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                                           Write(PrimaryKey);

            
            #line default
            #line hidden
WriteLiteral("\"}\r\n                },\r\n                tabs = new object[]{\r\n");

            
            #line 70 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 70 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                     for (var i = 0; i < tabs.Count; i++)
                    {
                        string typename = tabs[i].type.ToString();

            
            #line default
            #line hidden
WriteLiteral("                    ");

WriteLiteral("new{\r\n");

WriteLiteral("                    ");

WriteLiteral("  type = \"");

            
            #line 74 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                           Write(tabs[i].type);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n");

            
            #line 75 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                        switch(typename)
                        {
                            case "grid":

            
            #line default
            #line hidden
WriteLiteral("                    ");

WriteLiteral("  rowId = \"");

            
            #line 78 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                            Write(tabs[i].rowId);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n");

WriteLiteral("                    ");

WriteLiteral("  relationId = \"");

            
            #line 79 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                                 Write(tabs[i].relationship);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n");

WriteLiteral("                    ");

WriteLiteral("  postFields = new string[] { ");

            
            #line 80 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                                                     for (var j = 0; j < tabs[i].columns.Count; j++){
            
            #line default
            #line hidden
WriteLiteral("\"");

            
            #line 80 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                                                                                                        Write(tabs[i].columns[j].field);

            
            #line default
            #line hidden
WriteLiteral("\"");

            
            #line 80 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                                                                                                                                               if (j < tabs[i].columns.Count - 1){
            
            #line default
            #line hidden
            
            #line 80 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                                                                                                                                                                              Write(",");

            
            #line default
            #line hidden
            
            #line 80 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                                                                                                                                                                                        } }
            
            #line default
            #line hidden
WriteLiteral("},\r\n");

            
            #line 81 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                                break;
                            case "form":

            
            #line default
            #line hidden
WriteLiteral("                    ");

WriteLiteral("  primaryKeys = new string[]{\"");

            
            #line 83 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                                               Write(tabs[i].relationship);

            
            #line default
            #line hidden
WriteLiteral("\"},\r\n");

            
            #line 84 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                                break;
                            default:
                                break;
                        }

            
            #line default
            #line hidden
WriteLiteral("                    ");

WriteLiteral("  defaults = new {");

            
            #line 88 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                                         for (var j = 0; j < tabs[i].columns.Count; j++){
            
            #line default
            #line hidden
            
            #line 88 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                                                                                           Write(tabs[i].columns[j].field);

            
            #line default
            #line hidden
WriteLiteral(" = \"\"");

            
            #line 88 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                                                                                                                                      if (j < tabs[i].columns.Count - 1){
            
            #line default
            #line hidden
            
            #line 88 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                                                                                                                                                                     Write(",");

            
            #line default
            #line hidden
            
            #line 88 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                                                                                                                                                                               }}
            
            #line default
            #line hidden
WriteLiteral("}\r\n");

            
            #line 89 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                        

            
            #line default
            #line hidden
WriteLiteral("                    ");

WriteLiteral("}");

            
            #line 90 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                        if (i < tabs.Count - 1) {
            
            #line default
            #line hidden
            
            #line 90 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                                             Write(",");

            
            #line default
            #line hidden
            
            #line 90 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                                                       }
            
            #line default
            #line hidden
WriteLiteral("    \r\n");

            
            #line 91 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                }\r\n            };\r\n            return View(model);\r\n        }\r\n  " +
"  }\r\n\r\n    public class ");

            
            #line 98 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
             Write(controller);

            
            #line default
            #line hidden
WriteLiteral("ApiController : ApiController\r\n    {\r\n        public dynamic GetPageData(string i" +
"d)\r\n        {\r\n            var masterService = new ");

            
            #line 102 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                                Write(mainTable);

            
            #line default
            #line hidden
WriteLiteral("Service();\r\n            var pQuery = ParamQuery.Instance().Where(\"");

            
            #line 103 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                                                 Write(PrimaryKey);

            
            #line default
            #line hidden
WriteLiteral("\", id);\r\n\r\n             var result = new {\r\n                //主表数据\r\n             " +
"   form = masterService.GetModel(pQuery),\r\n                scrollKeys = masterSe" +
"rvice.ScrollKeys(\"");

            
            #line 108 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                                                  Write(PrimaryKey);

            
            #line default
            #line hidden
WriteLiteral("\", id),\r\n\r\n                //明细数据\r\n");

            
            #line 111 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                
            
            #line default
            #line hidden
            
            #line 111 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                 for (var i = 0; i < tabs.Count; i++)
                {
                    if (tabs[i].type.ToString()=="grid")
                    {

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral("tab");

            
            #line 115 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                 Write(i);

            
            #line default
            #line hidden
WriteLiteral(" = new ");

            
            #line 115 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                            Write(tabs[i].subtable);

            
            #line default
            #line hidden
WriteLiteral("Service().GetDynamicList(");

            
            #line 115 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                                                                       Write(Html.Raw(PrimaryKey==tabs[i].relationship.ToString()?"pQuery":"ParamQuery.Instance().Where(\"" + tabs[i].relationship +"\", id)"));

            
            #line default
            #line hidden
WriteLiteral(")");

            
            #line 115 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                                                                                                                                                                                                                if (i < tabs.Count - 1) {
            
            #line default
            #line hidden
            
            #line 115 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                                                                                                                                                                                                                                     Write(",");

            
            #line default
            #line hidden
            
            #line 115 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                                                                                                                                                                                                                                               }
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 116 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                    }
                    else if (tabs[i].type.ToString()=="form")
                    {

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral("tab");

            
            #line 119 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                 Write(i);

            
            #line default
            #line hidden
WriteLiteral(" = new ");

            
            #line 119 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                            Write(tabs[i].subtable);

            
            #line default
            #line hidden
WriteLiteral("Service().GetModel(");

            
            #line 119 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                                                                 Write(Html.Raw(PrimaryKey==tabs[i].relationship.ToString()?"pQuery":"ParamQuery.Instance().Where(\"" + tabs[i].relationship +"\", id)"));

            
            #line default
            #line hidden
WriteLiteral(")");

            
            #line 119 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                                                                                                                                                                                                          if (i < tabs.Count - 1) {
            
            #line default
            #line hidden
            
            #line 119 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                                                                                                                                                                                                                               Write(",");

            
            #line default
            #line hidden
            
            #line 119 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                                                                                                                                                                                                                                         }
            
            #line default
            #line hidden
WriteLiteral("      \r\n");

            
            #line 120 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                    }
                }

            
            #line default
            #line hidden
WriteLiteral("            };\r\n            return result;\r\n        }\r\n\r\n        [System.Web.Http" +
".HttpPost]\r\n        public void Audit(string id, JObject data)\r\n        {\r\n     " +
"       var pUpdate = ParamUpdate.Instance()\r\n                .Update(\"");

            
            #line 130 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                    Write(mainTable);

            
            #line default
            #line hidden
WriteLiteral(@""")
                .Column(""ApproveState"", data[""status""])
                .Column(""ApproveRemark"", data[""comment""])
                .Column(""ApprovePerson"", FormsAuth.GetLoginer().UserName)
                .Column(""ApproveDate"", DateTime.Now)
                .Where(""");

            
            #line 135 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                   Write(PrimaryKey);

            
            #line default
            #line hidden
WriteLiteral("\", id);\r\n\r\n            var service = new ");

            
            #line 137 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                          Write(mainTable);

            
            #line default
            #line hidden
WriteLiteral(@"Service();
            var rowsAffected = service.Update(pUpdate);
            MvcHelper.ThrowHttpExceptionWhen(rowsAffected < 0, ""单据审核失败[BillNo={0}]，请重试或联系管理员！"", id);
        }
  
        //todo 改成支持多个Tab
        // 地址：GET api/mms/@(controller)/getnewrowid 预取得新的明细表的行号
        public string GetNewRowId(string type,string key,int");

WriteLiteral(" qty=1)");

WriteLiteral("\r\n        {\r\n            switch (type)\r\n            {\r\n");

            
            #line 148 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
 for (var i = 0; i < tabs.Count; i++)
{
if(tabs[i].type == "grid")
{

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral("case \"grid");

            
            #line 152 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                        Write(i);

            
            #line default
            #line hidden
WriteLiteral("\":\r\n");

WriteLiteral("                ");

WriteLiteral("    var service");

            
            #line 153 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                             Write(i);

            
            #line default
            #line hidden
WriteLiteral(" = new ");

            
            #line 153 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                                        Write(tabs[i].subtable);

            
            #line default
            #line hidden
WriteLiteral("Service();\r\n");

WriteLiteral("                ");

WriteLiteral("    return service");

            
            #line 154 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                                Write(i);

            
            #line default
            #line hidden
WriteLiteral(".GetNewKey(\"");

            
            #line 154 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                                               Write(tabs[i].rowId);

            
            #line default
            #line hidden
WriteLiteral("\", \"maxplus\", qty, ParamQuery.Instance().Where(\"");

            
            #line 154 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                                                                                                              Write(tabs[i].relationship);

            
            #line default
            #line hidden
WriteLiteral("\", key));\r\n");

            
            #line 155 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
}
}

            
            #line default
            #line hidden
WriteLiteral(@"                default:
                    return """";
            }
        }
  
        // 地址：POST api/mms/send 功能：保存收料单数据
        [System.Web.Http.HttpPost]
        public void Edit(dynamic data)
        {
            var formWrapper = RequestWrapper.Instance().SetXml(");

WriteLiteral("@\"\r\n<settings>\r\n    <table>\r\n");

WriteLiteral("        ");

            
            #line 169 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
   Write(mainTable);

            
            #line default
            #line hidden
WriteLiteral("\r\n    </table>\r\n    <where>\r\n        <c column=\'");

            
            #line 172 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
              Write(PrimaryKey);

            
            #line default
            #line hidden
WriteLiteral("\' symbol=\'equal\'></c>\r\n    </where>\r\n</settings>\");\r\n\r\n            var tabsWrappe" +
"r = new List<RequestWrapper>();\r\n");

            
            #line 177 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
            
            
            #line default
            #line hidden
            
            #line 177 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
             for (var i = 0; i < tabs.Count; i++)
            {
                if(tabs[i].type.ToString() == "grid")
                {

            
            #line default
            #line hidden
WriteLiteral("            tabsWrapper.Add(RequestWrapper.Instance().SetXml(");

WriteLiteral("@\"\r\n");

WriteLiteral("<settings>\r\n");

WriteLiteral("    <table>");

            
            #line 183 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
        Write(tabs[i].subtable);

            
            #line default
            #line hidden
WriteLiteral("</table>\r\n");

WriteLiteral("    <where>\r\n");

            
            #line 185 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
    foreach(var item in tabs[i].primaryKeys)
    {

            
            #line default
            #line hidden
WriteLiteral("        <c column=\'");

            
            #line 187 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                Write(item);

            
            #line default
            #line hidden
WriteLiteral("\' symbol=\'equal\'></c>      \r\n");

            
            #line 188 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    </where>\r\n");

WriteLiteral("</settings>\"));\r\n");

            
            #line 191 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                }
                else if(tabs[i].type.ToString() == "form")
                {

            
            #line default
            #line hidden
WriteLiteral("            tabsWrapper.Add(RequestWrapper.Instance().SetXml(");

WriteLiteral("@\"\r\n");

WriteLiteral("<settings>\r\n");

WriteLiteral("    <table>");

            
            #line 196 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
        Write(tabs[i].subtable);

            
            #line default
            #line hidden
WriteLiteral("</table>\r\n");

WriteLiteral("    <where>\r\n");

WriteLiteral("        <c column=\'");

            
            #line 198 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                Write(tabs[i].relationship);

            
            #line default
            #line hidden
WriteLiteral("\' symbol=\'equal\'></c>\r\n");

WriteLiteral("    </where>\r\n");

WriteLiteral("</settings>\"));\r\n");

            
            #line 201 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                }
            }

            
            #line default
            #line hidden
WriteLiteral("             \r\n            var service = new ");

            
            #line 204 "..\..\Areas\Sys\Views\Generator\TemplateEditController.cshtml"
                          Write(mainTable);

            
            #line default
            #line hidden
WriteLiteral("Service();\r\n            var result = service.Edit(data, formWrapper, tabsWrapper)" +
";\r\n        }\r\n    }\r\n}");

        }
    }
}
#pragma warning restore 1591
