#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zephyr.Web.Sys.Areas.Sys.Views.User
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Sys/Views/User/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Index()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Areas\Sys\Views\User\Index.cshtml"
  
    ViewBag.Title = "title";
    Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("head", () => {

WriteLiteral("\r\n        <style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(@">
            div#navigation{background:white}
            div#wrapper{float:right;width:100%;margin-left:-185px}
            div#content{margin-left:185px}
            div#navigation{float:left;width:180px}
            .datagrid-cell a{color:black;}
            .datagrid-cell a:hover{color:red;}
        </style>
");

});

WriteLiteral("\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n        ");

WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 20 "..\..\Areas\Sys\Views\User\Index.cshtml"
   Write(Scripts.Render("~/Resource/Sys/Organize.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 21 "..\..\Areas\Sys\Views\User\Index.cshtml"
   Write(Scripts.Render("~/Resource/Sys/User.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n           using(\'validatebox\');\r\n           var data = ");

            
            #line 24 "..\..\Areas\Sys\Views\User\Index.cshtml"
                 Write(Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(Model)));

            
            #line default
            #line hidden
WriteLiteral(@";
            var formatterButton = function (value, row) {
                var dataStr = JSON.stringify({UserCode:row.UserCode,UserName:row.UserName,_isnew:row._isnew});
                var html = '<a href=""#"" onclick=\'setOrganize(' + dataStr + ')\'><span class=""icon icon-org"">&nbsp;</span>[设置机构]</a>';
                html += '<a href=""#"" onclick=\'setRole(' + dataStr + ')\' style=""margin-left:10px""><span class=""icon icon-group"">&nbsp;</span>[设置角色]</a>';
                html += '<a href=""#"" onclick=\'userSetting(' + dataStr + ')\' style=""margin-left:10px""><span class=""icon icon-wrench_orange"">&nbsp;</span>[用户设置]</a>';
                return html;
           };
        </script>
");

});

WriteLiteral("\r\n<div");

WriteLiteral(" id=\"container\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" id=\"wrapper\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" id=\"content\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"z-toolbar\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" id=\"a_refresh\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" plain=\"true\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-arrow_refresh\"");

WriteLiteral(" title=\"刷新\"");

WriteLiteral(" data-bind=\"click:refreshClick\"");

WriteLiteral(">刷新</a>\r\n                <a");

WriteLiteral(" id=\"a_add\"");

WriteLiteral("     href=\"#\"");

WriteLiteral(" plain=\"true\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-add\"");

WriteLiteral(" title=\"新增\"");

WriteLiteral(" data-bind=\"click:addClick\"");

WriteLiteral(">新增</a>\r\n                <a");

WriteLiteral(" id=\"a_edit\"");

WriteLiteral("    href=\"#\"");

WriteLiteral(" plain=\"true\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-edit\"");

WriteLiteral(" data-bind=\"click:editClick\"");

WriteLiteral(" title=\"编辑\"");

WriteLiteral(">编辑</a>\r\n                <a");

WriteLiteral(" id=\"a_del\"");

WriteLiteral("     href=\"#\"");

WriteLiteral(" plain=\"true\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-cross\"");

WriteLiteral(" title=\"删除\"");

WriteLiteral(" data-bind=\"click:deleteClick\"");

WriteLiteral(">删除</a>\r\n                <a");

WriteLiteral(" id=\"a_save\"");

WriteLiteral("    href=\"#\"");

WriteLiteral(" plain=\"true\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-save\"");

WriteLiteral(" data-bind=\"click:saveClick\"");

WriteLiteral(" title=\"保存\"");

WriteLiteral(">保存</a>\r\n                <a");

WriteLiteral(" id=\"a_pwd\"");

WriteLiteral("     href=\"#\"");

WriteLiteral(" plain=\"true\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-key\"");

WriteLiteral(" data-bind=\"click:passwordClick\"");

WriteLiteral(" title=\"重置密码\"");

WriteLiteral(">重置密码</a>\r\n            </div>\r\n\r\n            <table");

WriteLiteral(" id=\"gridlist\"");

WriteLiteral(" data-bind=\"datagrid:grid\"");

WriteLiteral(">\r\n                 <thead>  \r\n                    <tr>  \r\n                      " +
"  <th");

WriteLiteral(" field=\"UserCode\"");

WriteLiteral("            sortable=\"true\"");

WriteLiteral(" align=\"left\"");

WriteLiteral("    width=\"70\"");

WriteLiteral("  editor=\"{type:\'validatebox\',options:{required:true}}\"");

WriteLiteral("  >用户编码   </th>  \r\n                        <th");

WriteLiteral(" field=\"UserName\"");

WriteLiteral("            sortable=\"true\"");

WriteLiteral(" align=\"left\"");

WriteLiteral("    width=\"80\"");

WriteLiteral("  editor=\"{type:\'validatebox\',options:{required:true}}\"");

WriteLiteral("  >用户名称     </th>  \r\n                        <th");

WriteLiteral(" field=\"Description\"");

WriteLiteral("         sortable=\"true\"");

WriteLiteral(" align=\"left\"");

WriteLiteral("    width=\"280\"");

WriteLiteral(" editor=\"text\"");

WriteLiteral("  >描述说明   </th>  \r\n                        <th");

WriteLiteral(" field=\"IsEnable\"");

WriteLiteral("            sortable=\"true\"");

WriteLiteral(" align=\"center\"");

WriteLiteral("    width=\"70\"");

WriteLiteral(" formatter=\"com.formatCheckbox\"");

WriteLiteral("  editor=\"{type:\'checkbox\',options:{on:1,off:0}}\"");

WriteLiteral(">是否启用   </th>  \r\n                        <th");

WriteLiteral(" field=\"LoginCount\"");

WriteLiteral("          sortable=\"true\"");

WriteLiteral(" align=\"right\"");

WriteLiteral("    width=\"60\"");

WriteLiteral(" >登陆次数       </th>  \r\n                        <th");

WriteLiteral(" field=\"LastLoginDate\"");

WriteLiteral("       sortable=\"true\"");

WriteLiteral(" align=\"center\"");

WriteLiteral("    width=\"120\"");

WriteLiteral(" formatter=\"com.formatTime\"");

WriteLiteral("  >最后登陆时间   </th>   \r\n                        <th");

WriteLiteral(" field=\"Permit\"");

WriteLiteral(" align=\"center\"");

WriteLiteral("    width=\"270\"");

WriteLiteral(" formatter=\"formatterButton\"");

WriteLiteral("> 操作     </th> \r\n                    </tr>                            \r\n         " +
"       </thead>      \r\n            </table> \r\n        </div>\r\n    </div>\r\n    <d" +
"iv");

WriteLiteral(" id=\"navigation\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" title=\"组织机构\"");

WriteLiteral(" style=\"width: 180px;\"");

WriteLiteral(" class=\"easyui-panel\"");

WriteLiteral(" data-options=\"title: \'组织机构\', iconCls: \'icon-org\', height: $(window).height() - 4" +
" \"");

WriteLiteral(">\r\n            <ul");

WriteLiteral(" data-bind=\"easyuiTree:tree\"");

WriteLiteral("></ul>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n<script");

WriteLiteral(" type=\"text/html\"");

WriteLiteral(" id=\"setorganize-template\"");

WriteLiteral(@">
    <div style=""margin:5px;"">
        <div style=""border-bottom:1px solid #CCC; margin-bottom:5px;"">
            <span id=""role_name"" class=""icon32 icon-user-edit32"" style=""padding-left:48px;font-weight:bold; font-size:14px;color:#666;"" data-bind=""text:UserName"">刘会胜</span> 
        </div>
        <div> 所属机构：</div>
        <div data-bind=""html:graph""  style=""height:315px;overflow:auto;""></div>
    </div>
    <div style=""text-align:center;"">
        <a class=""easyui-linkbutton"" data-options=""iconCls:'icon-ok'"" data-bind=""click:confirmClick"" href=""javascript:void(0)""  >确定</a>  
        <a class=""easyui-linkbutton"" data-options=""iconCls:'icon-cancel'"" data-bind=""click:cancelClick"" href=""javascript:void(0)"">取消</a> 
    </div>
</script> 

<script");

WriteLiteral(" type=\"text/html\"");

WriteLiteral(" id=\"setrole-template\"");

WriteLiteral(@">
    <style type=""text/css"">
        .listview{ margin:0 !important;}
        .listview li{width:100px !important;background-color:skyblue !important;float:left;margin:3px;}
    </style>
    <div style=""margin:5px;height:370px;overflow:auto;""  >
        <div style=""border-bottom:1px solid #CCC; margin-bottom:5px;"">
            <span class=""icon32 icon-user-edit32"" style=""padding-left:48px;font-weight:bold; font-size:14px;color:#666;"" data-bind=""text:UserName"">刘会胜</span> 
        </div>
        <div> 拥有角色(请点击勾选)：</div>
        <div class=""metrouicss"">
            <ul class=""listview""></ul>
        </div>
    </div>
    <div style=""text-align:center;"">
        <a class=""easyui-linkbutton"" data-options=""iconCls:'icon-ok'"" data-bind=""click:confirmClick"" href=""javascript:void(0)""  >确定</a>  
        <a class=""easyui-linkbutton"" data-options=""iconCls:'icon-cancel'"" data-bind=""click:cancelClick"" href=""javascript:void(0)"">取消</a> 
    </div>
</script>

<script");

WriteLiteral(" type=\"text/html\"");

WriteLiteral(" id=\"manage-template\"");

WriteLiteral(@">
    <style type=""text/css"">
        .datagrid-wrap{border-width:0 0 1px 0;}
        .datagrid-toolbar{background-color:#E0ECFF !important}
    </style>

    <table data-bind=""datagrid:grid"">
        <thead>
            <th field=""ID"" hidden=""true""></th>
            <th field=""UserCode"" hidden=""true""></th>
            <th field=""SettingCode""    align=""left"" editor=""{type:'validatebox',options:{required:true}}"" width=""100"">设置编码   </th>  
            <th field=""SettingValue""   align=""left"" editor=""text""    width=""240"" >设定值  </th>
            <th field=""Description""    align=""left"" editor=""text""    width=""210""  >描述   </th>  
        </thead>
    </table>
    
    <div style=""text-align:center;margin:5px;"">
        <a class=""easyui-linkbutton"" data-options=""iconCls:'icon-ok'"" data-bind=""click:confirmClick"" href=""javascript:void(0)""  >确定</a>  
        <a class=""easyui-linkbutton"" data-options=""iconCls:'icon-cancel'"" data-bind=""click:cancelClick"" href=""javascript:void(0)"">取消</a> 
    </div>
</script>   

<script");

WriteLiteral(" type=\"text/html\"");

WriteLiteral(" id=\"tr-node-template\"");

WriteLiteral(@">
    <tr class=""tr-node""><td align=""center"" valign=""top"" colspan=""{0}"">
	    <table align=""center"" style=""border:solid 2px"" border=""1"" cellpadding=""2"" cellspacing=""0"">
	        <tr>
	            <td class=""td-node"" id='td{3}' data-node='{2}' align=""center"" valign=""top"" style=""background-color:#f6f6ff;cursor:pointer;padding:2px;"">{1}</td>
	        </tr>
	    </table>
    </td></tr>
    </script>

<script");

WriteLiteral(" type=\"text/html\"");

WriteLiteral(" id=\"tr-hline-template\"");

WriteLiteral(@">
    <tr class=""tr-hline"">
        <td colspan=""1"">
            <table width=""100%"" height=""100%"" border=""0"" cellpadding=""0"" cellspacing=""0"">
                <tbody>
                    <tr>
                        <td width=""50%"" style=""background:url(/Content/images/tree/Tree_Empty.gif)""></td>
                        <td width=""3px"" height=""3px"" ><img src=""/Content/images/tree/Tree_Dot.gif"" border=""0""></td>
                        <td width=""50%"" style=""background:url(/Content/images/tree/Tree_Dot.gif)""></td>
                    </tr>
                </tbody>
            </table>
        </td>
        <td style=""background:url(/Content/images/tree/Tree_Dot.gif)"" colspan=""{0}""></td>
        <td colspan=""1"">
            <table width=""100%"" height=""100%"" border=""0"" cellpadding=""0"" cellspacing=""0"">
                <tbody>
                    <tr>
                        <td width=""50%"" style=""background:url(/Content/images/tree/Tree_Dot.gif)""></td>
                        <td width=""3px"" height=""3px"" ><img src=""/Content/images/tree/Tree_Dot.gif"" border=""0""></td>
                        <td width=""50%"" style=""background:url(/Content/images/tree/Tree_Empty.gif)""></td>
                    </tr>
                </tbody>
            </table>
        </td>
    </tr>
</script>    
 ");

        }
    }
}
#pragma warning restore 1591
