#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zephyr.Web.Mvc.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Layout.cshtml")]
    public partial class Layout : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Layout()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!doctype html>\r\n<html");

WriteLiteral(" lang=\"zh\"");

WriteLiteral(">\r\n    <head>\r\n        <meta");

WriteLiteral(" http-equiv=\"Content-Type\"");

WriteLiteral(" content=\"text/html; charset=utf-8;no-cache\"");

WriteLiteral("/>\r\n        <title>");

            
            #line 5 "..\..\Views\Shared\_Layout.cshtml"
          Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 186), Tuple.Create("\"", 213)
, Tuple.Create(Tuple.Create("", 193), Tuple.Create<System.Object, System.Int32>(Href("~/Images/favicon.ico")
, 193), false)
);

WriteLiteral(" rel=\"shortcut icon\"");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(" />\r\n        <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width\"");

WriteLiteral(" />\r\n");

WriteLiteral("        ");

            
            #line 8 "..\..\Views\Shared\_Layout.cshtml"
   Write(Styles.Render("~/Content/css/base"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 381), Tuple.Create("\"", 422)
, Tuple.Create(Tuple.Create("", 388), Tuple.Create<System.Object, System.Int32>(Href("~/Content/css/btns/sexybuttons.css")
, 388), false)
);

WriteLiteral("  rel=\"Stylesheet\"");

WriteLiteral("/>\r\n        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 458), Tuple.Create("\"", 495)
, Tuple.Create(Tuple.Create("", 465), Tuple.Create<System.Object, System.Int32>(Href("~/Content/css/btns/css3btn.css")
, 465), false)
);

WriteLiteral("  rel=\"Stylesheet\"");

WriteLiteral("/>\r\n        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 531), Tuple.Create("\"", 593)
, Tuple.Create(Tuple.Create("", 538), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/jquery-plugins/showloading/showLoading.css")
, 538), false)
);

WriteLiteral("  rel=\"Stylesheet\"");

WriteLiteral("/>\r\n");

WriteLiteral("        ");

            
            #line 12 "..\..\Views\Shared\_Layout.cshtml"
   Write(StylesLess.Render("~/Content/css/theme/" + AppLoginer.Theme));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 702), Tuple.Create("\"", 770)
, Tuple.Create(Tuple.Create("", 708), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/jquery/jquery-")
, 708), false)
            
            #line 13 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 735), Tuple.Create<System.Object, System.Int32>(AppSettings.JqueryVersion
            
            #line default
            #line hidden
, 735), false)
, Tuple.Create(Tuple.Create("", 763), Tuple.Create(".min.js", 763), true)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" ></script>\r\n");

WriteLiteral("        ");

            
            #line 14 "..\..\Views\Shared\_Layout.cshtml"
   Write(RenderSection("head", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </head>\r\n    <body");

WriteLiteral(" class=\"z-body\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 17 "..\..\Views\Shared\_Layout.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n        <!--加载脚本库-->\r\n");

WriteLiteral("        ");

            
            #line 19 "..\..\Views\Shared\_Layout.cshtml"
   Write(System.Web.Optimization.Scripts.Render("~/Content/js/librarys"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <!--加载easyui加载器-->\r\n        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 1081), Tuple.Create("\"", 1197)
, Tuple.Create(Tuple.Create("", 1087), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/easyui/")
, 1087), false)
            
            #line 21 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1107), Tuple.Create<System.Object, System.Int32>(AppSettings.EasyuiVersion
            
            #line default
            #line hidden
, 1107), false)
, Tuple.Create(Tuple.Create("", 1133), Tuple.Create("/easyloader.js?locale=", 1133), true)
            
            #line 21 "..\..\Views\Shared\_Layout.cshtml"
                                , Tuple.Create(Tuple.Create("", 1155), Tuple.Create<System.Object, System.Int32>(AppLoginer.Locale
            
            #line default
            #line hidden
, 1155), false)
, Tuple.Create(Tuple.Create("", 1173), Tuple.Create("&theme=", 1173), true)
            
            #line 21 "..\..\Views\Shared\_Layout.cshtml"
                                                         , Tuple.Create(Tuple.Create("", 1180), Tuple.Create<System.Object, System.Int32>(AppLoginer.Theme
            
            #line default
            #line hidden
, 1180), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("        ");

            
            #line 22 "..\..\Views\Shared\_Layout.cshtml"
   Write(RenderSection("scripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <!--加载图标库CSS-->\r\n        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1300), Tuple.Create("\"", 1334)
, Tuple.Create(Tuple.Create("", 1307), Tuple.Create<System.Object, System.Int32>(Href("~/Content/css/icon/icon.css")
, 1307), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    </body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
