#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zephyr.Web.Sys.Areas.Sys.Views.Menu
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Sys/Views/Menu/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Index()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Areas\Sys\Views\Menu\Index.cshtml"
  
    ViewBag.Title = "title";
    Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n \r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 8 "..\..\Areas\Sys\Views\Menu\Index.cshtml"
   Write(Scripts.Render("~/Resource/Sys/Menu.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
            using(""lookup"", easyuifix.datagrid_editor_extend);
            ko.bindingViewModel(new viewModel());
            using(['validatebox','combotree','numberspinner'],easyuifix.datagrid_editor_extend);
            var formatterParent = function (value, row) { return row.ParentName };
            var formatterButton = function (value, row) { return (row.URL&&row.URL!='#')?'<a href=""#"" onclick=""setButton(\'' + row.MenuCode + '\')""><span class=""icon icon-set2"">&nbsp;</span>[设置按钮]</a>':''; };
        </script>
");

});

WriteLiteral("        <div");

WriteLiteral(" class=\"z-toolbar\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" id=\"a_refresh\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" plain=\"true\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-arrow_refresh\"");

WriteLiteral(" title=\"刷新\"");

WriteLiteral(" data-bind=\"click:refreshClick\"");

WriteLiteral(">刷新</a>\r\n            <a");

WriteLiteral(" id=\"a_add\"");

WriteLiteral("    href=\"#\"");

WriteLiteral(" plain=\"true\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-add\"");

WriteLiteral(" title=\"新增\"");

WriteLiteral(" data-bind=\"click:addClick\"");

WriteLiteral(">新增</a>\r\n            <a");

WriteLiteral(" id=\"a_edit\"");

WriteLiteral("   href=\"#\"");

WriteLiteral(" plain=\"true\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-edit\"");

WriteLiteral(" data-bind=\"click:editClick\"");

WriteLiteral(" title=\"编辑\"");

WriteLiteral(">编辑</a>\r\n            <a");

WriteLiteral(" id=\"a_del\"");

WriteLiteral("    href=\"#\"");

WriteLiteral(" plain=\"true\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-cross\"");

WriteLiteral(" title=\"删除\"");

WriteLiteral(" data-bind=\"click:deleteClick\"");

WriteLiteral(">删除</a>\r\n            <a");

WriteLiteral(" id=\"a_save\"");

WriteLiteral("  href=\"#\"");

WriteLiteral(" plain=\"true\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-save\"");

WriteLiteral(" data-bind=\"click:saveClick\"");

WriteLiteral(" title=\"保存\"");

WriteLiteral(">保存</a>\r\n        </div>\r\n        \r\n        <table");

WriteLiteral(" id=\"gridlist\"");

WriteLiteral(" data-bind=\"treegrid:grid\"");

WriteLiteral(">\r\n             <thead>  \r\n                <tr>  \r\n                    <th");

WriteLiteral(" field=\"_id\"");

WriteLiteral("  hidden=\"true\"");

WriteLiteral("></th>  \r\n                    <th");

WriteLiteral(" field=\"MenuName\"");

WriteLiteral("    align=\"left\"");

WriteLiteral("        width=\"150\"");

WriteLiteral(" editor=\"{type:\'validatebox\',options:{required: true }}\"");

WriteLiteral(">菜单名称   </th>  \r\n                    <th");

WriteLiteral(" field=\"MenuCode\"");

WriteLiteral("    align=\"left\"");

WriteLiteral("        width=\"80\"");

WriteLiteral("  editor=\"{type:\'validatebox\',options:{required: true }}\"");

WriteLiteral(">编码   </th>  \r\n                    <th");

WriteLiteral(" field=\"ParentCode\"");

WriteLiteral("  align=\"left\"");

WriteLiteral("        width=\"150\"");

WriteLiteral("  editor=\"combotree\"");

WriteLiteral(" formatter=\"formatterParent\"");

WriteLiteral(">上级菜单   </th>\r\n                    <th");

WriteLiteral(" field=\"IconClass\"");

WriteLiteral("   align=\"left\"");

WriteLiteral("        width=\"180\"");

WriteLiteral(" editor=\"{type:\'lookup\'}\"");

WriteLiteral(">图标     </th> \r\n                    <th");

WriteLiteral(" field=\"URL\"");

WriteLiteral("         align=\"left\"");

WriteLiteral("        width=\"180\"");

WriteLiteral(" editor=\"text\"");

WriteLiteral(">链接地址   </th> \r\n                    <th");

WriteLiteral(" field=\"IsVisible\"");

WriteLiteral("   align=\"center\"");

WriteLiteral("      width=\"60\"");

WriteLiteral(" editor=\"{type: \'checkbox\',options: {on: 1,off: 0}}\"");

WriteLiteral(" formatter=\"com.formatCheckbox\"");

WriteLiteral(" >是否可见</th> \r\n                    <th");

WriteLiteral(" field=\"IsEnable\"");

WriteLiteral("    align=\"center\"");

WriteLiteral("      width=\"60\"");

WriteLiteral(" editor=\"{type: \'checkbox\',options: {on: 1,off: 0}}\"");

WriteLiteral(" formatter=\"com.formatCheckbox\"");

WriteLiteral(" >是否启用</th> \r\n                    <th");

WriteLiteral(" field=\"MenuSeq\"");

WriteLiteral("     align=\"right\"");

WriteLiteral("       width=\"50\"");

WriteLiteral("  editor=\"text\"");

WriteLiteral(">排序</th> \r\n                    <th");

WriteLiteral(" field=\"Button\"");

WriteLiteral("      align=\"center\"");

WriteLiteral("      width=\"100\"");

WriteLiteral(" formatter=\"formatterButton\"");

WriteLiteral(">页面按钮 </th> \r\n                </tr>                            \r\n            </th" +
"ead>      \r\n        </table> \r\n\r\n\r\n<script");

WriteLiteral(" type=\"text/html\"");

WriteLiteral(" id=\"button-template\"");

WriteLiteral(">\r\n    <div style=\"margin:5px;height:320px;overflow:auto;\">\r\n        <style type=" +
"\"text/css\">\r\n            .listview{ margin:0 !important;}\r\n            .listview" +
" li{width:100px !important;background-color:#ECECFF !important;float:left;margin" +
":3px;overflow:hidden;}\r\n            .listview span{ font-size:14px !important;he" +
"ight:auto !important; white-space: nowrap;}\r\n            .listview .icon:before{" +
"content:\"\" !important}\r\n        </style>\r\n\r\n        <div style=\"border-bottom:1p" +
"x solid #CCC; margin-bottom:5px;\">\r\n            <span class=\"icon32 icon-setting" +
"s32\" style=\"padding-left:48px;font-weight:bold; font-size:14px;color:#666;\">请选择页" +
"面按钮</span> \r\n        </div>\r\n \r\n        <div class=\"metrouicss\">\r\n            <l" +
"abel class=\"input-control checkbox\" style=\"margin-top:6px;margin-left:3px;\">\r\n  " +
"              <input type=\"checkbox\" data-bind=\"checked:checkAll\"><span class=\"h" +
"elper\">全选</span>\r\n            </label>\r\n            <button class=\"image-button " +
"standart fg-color-white\" style=\"float:right\" data-bind=\"click:manageClick\">\r\n   " +
"         <i class=\"icon-grid-view bg-color-green\"></i>\r\n                管理按钮库\r\n " +
"           </button>\r\n            <ul class=\"listview\" data-bind=\"foreach: butto" +
"ns\" style=\"clear:both\">\r\n                <li data-bind=\"click:$parent.buttonClic" +
"k,css:{selected:Selected()>0}\"><span class=\"icon\" data-bind=\"text:ButtonName,css" +
":ButtonIcon\"></span></li>\r\n            </ul>\r\n        </div>\r\n \r\n    </div>\r\n   " +
" <div style=\"text-align:center;\">\r\n        <a class=\"easyui-linkbutton\" data-opt" +
"ions=\"iconCls:\'icon-ok\'\" data-bind=\"click:confirmClick\" href=\"javascript:void(0)" +
"\"  >确定</a>  \r\n        <a class=\"easyui-linkbutton\" data-options=\"iconCls:\'icon-c" +
"ancel\'\" data-bind=\"click:cancelClick\" href=\"javascript:void(0)\">取消</a> \r\n    </d" +
"iv>\r\n</script>\r\n\r\n<script");

WriteLiteral(" type=\"text/html\"");

WriteLiteral(" id=\"manage-template\"");

WriteLiteral(@">
    <style type=""text/css"">
        .datagrid-wrap{border-width:0 0 1px 0;}
        .datagrid-toolbar{background-color:#E0ECFF !important}
    </style>

    <table data-bind=""datagrid:grid"">
        <thead>
            <th field=""ButtonCode""    align=""left"" editor=""{type:'validatebox',options:{required:true}}""    width=""80""  >编码   </th>  
            <th field=""ButtonName""    align=""left"" editor=""{type:'validatebox',options:{required:true}}""    width=""70""  >名称   </th>  
            <th field=""ButtonIcon""    align=""left"" editor=""{type:'validatebox',options:{required:true}}""    width=""120"" >图标   </th> 
            <th field=""ButtonSeq""     align=""left"" editor=""text""    width=""50""  >排序   </th> 
            <th field=""Description""   align=""left"" editor=""text""    width=""200"" >备注说明   </th> 
        </thead>
    </table>
    
    <div style=""text-align:center;margin:5px;"">
        <a class=""easyui-linkbutton"" data-options=""iconCls:'icon-ok'"" data-bind=""click:confirmClick"" href=""javascript:void(0)""  >确定</a>  
        <a class=""easyui-linkbutton"" data-options=""iconCls:'icon-cancel'"" data-bind=""click:cancelClick"" href=""javascript:void(0)"">取消</a> 
    </div>
</script> ");

        }
    }
}
#pragma warning restore 1591
