#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zephyr.Web.Sys.Areas.Sys.Views.Code
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Sys/Views/Code/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Index()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Areas\Sys\Views\Code\Index.cshtml"
  
    ViewBag.Title = "title";
    Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("head", () => {

WriteLiteral("\r\n        <style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(@">
            div#navigation{background:white}
            div#wrapper{float:right;width:100%;margin-left:-185px}
            div#content{margin-left:185px}
            div#navigation{float:left;width:180px}
            .datagrid-cell a{color:black;}
            .datagrid-cell a:hover{color:red;}
        </style>
");

});

WriteLiteral("\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n        ");

WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 20 "..\..\Areas\Sys\Views\Code\Index.cshtml"
   Write(Scripts.Render("~/Resource/Sys/Organize.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 21 "..\..\Areas\Sys\Views\Code\Index.cshtml"
   Write(Scripts.Render("~/Resource/Sys/Code.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n           using(\'validatebox\');\r\n           var data = ");

            
            #line 24 "..\..\Areas\Sys\Views\Code\Index.cshtml"
                 Write(Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(Model)));

            
            #line default
            #line hidden
WriteLiteral(@";
            ko.bindingViewModel(new viewModel());
            var formatterButton = function (value, row) {
                var dataStr = JSON.stringify({UserCode:row.UserCode,UserName:row.UserName,_isnew:row._isnew});
                var html = '<a href=""#"" onclick=\'setOrganize(' + dataStr + ')\'><span class=""icon icon-org"">&nbsp;</span>[设置机构]</a>';
                html += '<a href=""#"" onclick=\'setRole(' + dataStr + ')\' style=""margin-left:10px""><span class=""icon icon-group"">&nbsp;</span>[设置角色]</a>';
               return html;
           };
        </script>
");

});

WriteLiteral("\r\n<div");

WriteLiteral(" id=\"container\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" id=\"wrapper\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" id=\"content\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"z-toolbar\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" id=\"a_refresh\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" plain=\"true\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-arrow_refresh\"");

WriteLiteral(" title=\"刷新\"");

WriteLiteral(" data-bind=\"click:refreshClick\"");

WriteLiteral(">刷新</a>\r\n                <a");

WriteLiteral(" id=\"a_add\"");

WriteLiteral("    href=\"#\"");

WriteLiteral(" plain=\"true\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-add\"");

WriteLiteral(" title=\"新增\"");

WriteLiteral(" data-bind=\"click:addClick\"");

WriteLiteral(">新增</a>\r\n                <a");

WriteLiteral(" id=\"a_edit\"");

WriteLiteral("   href=\"#\"");

WriteLiteral(" plain=\"true\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-edit\"");

WriteLiteral(" data-bind=\"click:editClick\"");

WriteLiteral(" title=\"编辑\"");

WriteLiteral(">编辑</a>\r\n                <a");

WriteLiteral(" id=\"a_del\"");

WriteLiteral("    href=\"#\"");

WriteLiteral(" plain=\"true\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-cross\"");

WriteLiteral(" title=\"删除\"");

WriteLiteral(" data-bind=\"click:deleteClick\"");

WriteLiteral(">删除</a>\r\n                <a");

WriteLiteral(" id=\"a_save\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" plain=\"true\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-save\"");

WriteLiteral(" data-bind=\"click:saveClick\"");

WriteLiteral(" title=\"保存\"");

WriteLiteral(">保存</a>\r\n                <a");

WriteLiteral(" id=\"a_save\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" plain=\"true\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-node_tree\"");

WriteLiteral(" data-bind=\"click:typeClick\"");

WriteLiteral(" title=\"管理类别\"");

WriteLiteral(">管理类别</a>\r\n            </div>\r\n\r\n            <table");

WriteLiteral(" id=\"gridlist\"");

WriteLiteral(" data-bind=\"treegrid:grid\"");

WriteLiteral(">\r\n                 <thead>  \r\n                    <tr>  \r\n                      " +
"  <th");

WriteLiteral(" field=\"CodeType\"");

WriteLiteral("            hidden=\"true\"");

WriteLiteral("></th>\r\n                        <th");

WriteLiteral(" field=\"Code\"");

WriteLiteral("                sortable=\"true\"");

WriteLiteral(" align=\"left\"");

WriteLiteral("    width=\"100\"");

WriteLiteral("  editor=\"{type:\'validatebox\',options:{required:true}}\"");

WriteLiteral("  >编号   </th> \r\n                        <th");

WriteLiteral(" field=\"Value\"");

WriteLiteral("               sortable=\"true\"");

WriteLiteral(" align=\"left\"");

WriteLiteral("    width=\"100\"");

WriteLiteral("  editor=\"{type:\'validatebox\',options:{required:true}}\"");

WriteLiteral("  >编码   </th>  \r\n                        <th");

WriteLiteral(" field=\"Text\"");

WriteLiteral("                sortable=\"true\"");

WriteLiteral(" align=\"left\"");

WriteLiteral("    width=\"100\"");

WriteLiteral("  editor=\"{type:\'validatebox\',options:{required:true}}\"");

WriteLiteral("  >文本     </th>  \r\n                        <th");

WriteLiteral(" field=\"ParentCode\"");

WriteLiteral("          sortable=\"true\"");

WriteLiteral(" align=\"left\"");

WriteLiteral("    width=\"70\"");

WriteLiteral("  editor=\"text\"");

WriteLiteral("  >上级编号   </th> \r\n                        <th");

WriteLiteral(" field=\"Description\"");

WriteLiteral("         sortable=\"true\"");

WriteLiteral(" align=\"left\"");

WriteLiteral("    width=\"180\"");

WriteLiteral(" editor=\"text\"");

WriteLiteral("  >描述说明   </th>  \r\n                        <th");

WriteLiteral(" field=\"IsEnable\"");

WriteLiteral("            sortable=\"true\"");

WriteLiteral(" align=\"center\"");

WriteLiteral("    width=\"70\"");

WriteLiteral(" formatter=\"com.formatCheckbox\"");

WriteLiteral("  editor=\"{type:\'checkbox\',options:{on:1,off:0}}\"");

WriteLiteral(">是否启用   </th>  \r\n                        <th");

WriteLiteral(" field=\"IsDefault\"");

WriteLiteral("           sortable=\"true\"");

WriteLiteral(" align=\"center\"");

WriteLiteral("    width=\"70\"");

WriteLiteral(" formatter=\"com.formatCheckbox\"");

WriteLiteral("  editor=\"{type:\'checkbox\',options:{on:1,off:0}}\"");

WriteLiteral(">是否默认   </th> \r\n                        <th");

WriteLiteral(" field=\"Seq\"");

WriteLiteral("                 sortable=\"true\"");

WriteLiteral(" align=\"right\"");

WriteLiteral("    width=\"60\"");

WriteLiteral("  editor=\"text\"");

WriteLiteral(">排序       </th>  \r\n                    </tr>                            \r\n       " +
"         </thead>      \r\n            </table> \r\n        </div>\r\n    </div>\r\n    " +
"<div");

WriteLiteral(" id=\"navigation\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" title=\"字典类别\"");

WriteLiteral(" style=\"width: 180px;\"");

WriteLiteral(" class=\"easyui-panel\"");

WriteLiteral(" data-options=\"title: \'字典类别\', iconCls: \'icon-node_tree\', height: $(window).height" +
"() - 4 \"");

WriteLiteral(">\r\n            <ul");

WriteLiteral(" data-bind=\"easyuiTree:tree\"");

WriteLiteral("></ul>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n<script");

WriteLiteral(" type=\"text/html\"");

WriteLiteral(" id=\"type-template\"");

WriteLiteral(@">
    <style type=""text/css"">
        .datagrid-wrap{border-width:0 0 1px 0;}
        /*.datagrid-toolbar{background-color:#E0ECFF !important}*/
    </style>

    <table data-bind=""datagrid:grid"">
        <thead>
            <th field=""CodeType""        sortable=""true"" align=""left""    width=""120"" editor=""{type:'validatebox',options:{required:true}}"">类别编码</th>
            <th field=""CodeTypeName""    sortable=""true"" align=""left""    width=""150"" editor=""{type:'validatebox',options:{required:true}}"">类别名称</th>
            <th field=""Description""     sortable=""true"" align=""left""    width=""200"" editor=""text""  >描述说明   </th>  
            <th field=""Seq""             sortable=""true"" align=""right""   width=""60""  editor=""text"">排序       </th>  
        </thead>
    </table>
    
    <div style=""text-align:center;margin:4px;"">
        <a class=""easyui-linkbutton"" data-options=""iconCls:'icon-ok'"" data-bind=""click:confirmClick"" href=""javascript:void(0)""  >确定</a>  
        <a class=""easyui-linkbutton"" data-options=""iconCls:'icon-cancel'"" data-bind=""click:cancelClick"" href=""javascript:void(0)"">取消</a> 
    </div>
</script> 
        
 ");

        }
    }
}
#pragma warning restore 1591
