#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zephyr.Web.Sys.Areas.Sys.Views.Organize
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Sys/Views/Organize/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Index()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Areas\Sys\Views\Organize\Index.cshtml"
  
    ViewBag.EasyuiVersion = "1.3.2";
    ViewBag.locale = "zh_CN";
    ViewBag.theme = Zephyr.Utils.CookiesHelper.GetCookies("theme");

            
            #line default
            #line hidden
WriteLiteral("\r\n<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n<html>\r\n    <h" +
"ead>\r\n        <meta");

WriteLiteral(" http-equiv=\"Content-Type\"");

WriteLiteral(" content=\"text/html; charset=utf-8\"");

WriteLiteral("/>\r\n        <title>");

            
            #line 10 "..\..\Areas\Sys\Views\Organize\Index.cshtml"
          Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 360), Tuple.Create("\"", 387)
, Tuple.Create(Tuple.Create("", 367), Tuple.Create<System.Object, System.Int32>(Href("~/Images/favicon.ico")
, 367), false)
);

WriteLiteral(" rel=\"shortcut icon\"");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(" />\r\n        <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width\"");

WriteLiteral(" />\r\n       \r\n        <!--加载共通CSS-->\r\n        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 542), Tuple.Create("\"", 571)
, Tuple.Create(Tuple.Create("", 549), Tuple.Create<System.Object, System.Int32>(Href("~/Content/css/base.css")
, 549), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n        <!--[if IE]><link");

WriteAttribute("href", Tuple.Create(" href=\"", 635), Tuple.Create("\"", 667)
, Tuple.Create(Tuple.Create("", 642), Tuple.Create<System.Object, System.Int32>(Href("~/Content/css/hack/ie.css")
, 642), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" /><![endif]-->\r\n\r\n        <!--加载960CSS框架-->\r\n        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 760), Tuple.Create("\"", 800)
, Tuple.Create(Tuple.Create("", 767), Tuple.Create<System.Object, System.Int32>(Href("~/Content/css/960/fluid/reset.css")
, 767), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral("  />\r\n        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 853), Tuple.Create("\"", 892)
, Tuple.Create(Tuple.Create("", 860), Tuple.Create<System.Object, System.Int32>(Href("~/Content/css/960/fluid/text.css")
, 860), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 944), Tuple.Create("\"", 983)
, Tuple.Create(Tuple.Create("", 951), Tuple.Create<System.Object, System.Int32>(Href("~/Content/css/960/fluid/grid.css")
, 951), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n        <!--[if IE 6]><link");

WriteAttribute("href", Tuple.Create(" href=\"", 1049), Tuple.Create("\"", 1087)
, Tuple.Create(Tuple.Create("", 1056), Tuple.Create<System.Object, System.Int32>(Href("~/Content/css/960/fluid/ie6.css")
, 1056), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" /><![endif]-->\r\n        <!--[if IE 7]><link");

WriteAttribute("href", Tuple.Create(" href=\"", 1165), Tuple.Create("\"", 1202)
, Tuple.Create(Tuple.Create("", 1172), Tuple.Create<System.Object, System.Int32>(Href("~/Content/css/960/fluid/ie.css")
, 1172), false)
);

WriteLiteral("  rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" /><![endif]-->\r\n \r\n        <!--加载按钮CSS-->\r\n        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1294), Tuple.Create("\"", 1331)
, Tuple.Create(Tuple.Create("", 1301), Tuple.Create<System.Object, System.Int32>(Href("~/Content/css/btns/css3btn.css")
, 1301), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1383), Tuple.Create("\"", 1424)
, Tuple.Create(Tuple.Create("", 1390), Tuple.Create<System.Object, System.Int32>(Href("~/Content/css/btns/sexybuttons.css")
, 1390), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    \r\n        <!--加载组件CSS-->\r\n        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1506), Tuple.Create("\"", 1568)
, Tuple.Create(Tuple.Create("", 1513), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/jquery-plugins/showloading/showLoading.css")
, 1513), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    \r\n        <!--加载样式修正CSS-->\r\n        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1652), Tuple.Create("\"", 1685)
, Tuple.Create(Tuple.Create("", 1659), Tuple.Create<System.Object, System.Int32>(Href("~/Content/css/hack/fix.css")
, 1659), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n        \r\n        <!--加载主题CSS-->\r\n");

WriteLiteral("        ");

            
            #line 36 "..\..\Areas\Sys\Views\Organize\Index.cshtml"
   Write(StylesLess.Render("~/Content/css/theme/" + AppLoginer.Theme));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n        <!--加载jQuery-->\r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1871), Tuple.Create("\"", 1939)
, Tuple.Create(Tuple.Create("", 1877), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/jquery/jquery-")
, 1877), false)
            
            #line 39 "..\..\Areas\Sys\Views\Organize\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1904), Tuple.Create<System.Object, System.Int32>(AppSettings.JqueryVersion
            
            #line default
            #line hidden
, 1904), false)
, Tuple.Create(Tuple.Create("", 1932), Tuple.Create(".min.js", 1932), true)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" ></script>\r\n    </head>\r\n    <body");

WriteLiteral(" class=\"z-body\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"z-toolbar\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" id=\"a_refresh\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" plain=\"true\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-arrow_refresh\"");

WriteLiteral(" title=\"刷新\"");

WriteLiteral(" data-bind=\"click:refreshClick\"");

WriteLiteral(">刷新</a>\r\n            <a");

WriteLiteral(" id=\"a_add\"");

WriteLiteral("    href=\"#\"");

WriteLiteral(" plain=\"true\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-add\"");

WriteLiteral(" title=\"新增\"");

WriteLiteral(" data-bind=\"click:addClick\"");

WriteLiteral(">新增</a>\r\n            <a");

WriteLiteral(" id=\"a_edit\"");

WriteLiteral("   href=\"#\"");

WriteLiteral(" plain=\"true\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-edit\"");

WriteLiteral(" data-bind=\"click:editClick\"");

WriteLiteral(" title=\"编辑\"");

WriteLiteral(">编辑</a>\r\n            <a");

WriteLiteral(" id=\"a_del\"");

WriteLiteral("    href=\"#\"");

WriteLiteral(" plain=\"true\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-cross\"");

WriteLiteral(" title=\"删除\"");

WriteLiteral(" data-bind=\"click:deleteClick\"");

WriteLiteral(">删除</a>\r\n            <a");

WriteLiteral(" id=\"a_role\"");

WriteLiteral("    href=\"#\"");

WriteLiteral(" plain=\"true\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-group\"");

WriteLiteral(" title=\"设置角色\"");

WriteLiteral(" data-bind=\"click:roleClick\"");

WriteLiteral(">设置角色</a>\r\n        </div>\r\n \r\n        <div");

WriteLiteral(" id=\"gridlist\"");

WriteLiteral(" class=\"wrapper\"");

WriteLiteral(" style=\"width: 100%; height: 100%; margin-top:15px;\"");

WriteLiteral("></div>\r\n \r\n        <script");

WriteLiteral(" type=\"text/html\"");

WriteLiteral(" id=\"edit-template\"");

WriteLiteral(@">
            <div class=""container_16"" style=""width:90%;margin:5%;"">  
                <div class=""grid_3 lbl"" >上级机构</div>  
                <div class=""grid_13 val"" ><input class=""z-text"" data-bind=""easyuiCombotree:combotree,combotreeValue:form.ParentCode"" /><span data-bind1=""text:form.ParentCode"" style=""margin:5px;""></span></div>
                <div class=""grid_3 lbl"">机构编码</div>  
                <div class=""grid_13 val""><input class=""z-txt easyui-validatebox"" style=""width:220px;"" data-bind=""value:form.OrganizeCode"" data-options=""required:true"" /></div>
                <div class=""grid_3 lbl"">机构名称</div>  
                <div class=""grid_13 val""><input class=""z-txt easyui-validatebox"" style=""width:220px;"" data-bind=""value:form.OrganizeName"" data-options=""required:true"" /></div>
                <div class=""grid_3 lbl"">备注</div>  
                <div class=""grid_13 val""><textarea class=""z-txt"" style=""width:220px;height:50px;"" data-bind=""value:form.Description""  ></textarea></div>
                <div class=""clear""></div>
            </div> 
            <div style=""text-align:center;"">
                <a class=""easyui-linkbutton"" data-options=""iconCls:'icon-ok'"" data-bind=""click:confirmClick"" href=""javascript:void(0)""  >确定</a>  
                <a class=""easyui-linkbutton"" data-options=""iconCls:'icon-cancel'"" data-bind=""click:cancelClick"" href=""javascript:void(0)"">取消</a> 
            </div>
        </script>

        <script");

WriteLiteral(" type=\"text/html\"");

WriteLiteral(" id=\"setrole-template\"");

WriteLiteral(@">
            <style type=""text/css"">
                .listview{ margin:0 !important;}
                .listview li{width:100px !important;background-color:skyblue !important;float:left;margin:3px;}
            </style>
            <div style=""margin:5px;height:370px;overflow:auto;""  >
                <div style=""border-bottom:1px solid #CCC; margin-bottom:5px;"">
                    <span class=""icon32 icon-org32"" style=""padding-left:48px;font-weight:bold; font-size:14px;color:#666;"" data-bind=""text:OrganizeName"">机构名称</span> 
                </div>
                <div> 拥有角色(请点击勾选)：</div>
                <div class=""metrouicss"">
                    <ul class=""listview""></ul>
                </div>
            </div>
            <div style=""text-align:center;"">
                <a class=""easyui-linkbutton"" data-options=""iconCls:'icon-ok'"" data-bind=""click:confirmClick"" href=""javascript:void(0)""  >确定</a>  
                <a class=""easyui-linkbutton"" data-options=""iconCls:'icon-cancel'"" data-bind=""click:cancelClick"" href=""javascript:void(0)"">取消</a> 
            </div>
        </script>

         <script");

WriteLiteral(" type=\"text/html\"");

WriteLiteral(" id=\"tr-node-template\"");

WriteLiteral(@">
            <tr class=""tr-node""><td align=""center"" valign=""top"" colspan=""{0}"">
	            <table align=""center"" style=""border:solid 2px"" border=""1"" cellpadding=""2"" cellspacing=""0"">
	                <tr>
	                    <td class=""td-node"" id='td{3}' data-node='{2}' align=""center"" valign=""top"" style=""background-color:#f6f6ff;cursor:pointer;padding:2px;"">{1}</td>
	                </tr>
	            </table>
            </td></tr>
        </script>

         <script");

WriteLiteral(" type=\"text/html\"");

WriteLiteral(" id=\"tr-hline-template\"");

WriteLiteral(">\r\n             <tr class=\"tr-hline\">\r\n                <td colspan=\"1\">\r\n        " +
"            <table width=\"100%\" height=\"100%\" border=\"0\" cellpadding=\"0\" cellspa" +
"cing=\"0\">\r\n                        <tbody>\r\n                            <tr>\r\n  " +
"                              <td width=\"50%\" style=\"background:url(/Content/ima" +
"ges/tree/Tree_Empty.gif)\"></td>\r\n                                <td width=\"3px\"" +
" height=\"3px\" ><img src=\"/Content/images/tree/Tree_Dot.gif\" border=\"0\"></td>\r\n  " +
"                              <td width=\"50%\" style=\"background:url(/Content/ima" +
"ges/tree/Tree_Dot.gif)\"></td>\r\n                            </tr>\r\n              " +
"          </tbody>\r\n                    </table>\r\n                </td>\r\n       " +
"         <td style=\"background:url(/Content/images/tree/Tree_Dot.gif)\" colspan=\"" +
"{0}\"></td>\r\n                <td colspan=\"1\">\r\n                    <table width=\"" +
"100%\" height=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n               " +
"         <tbody>\r\n                            <tr>\r\n                            " +
"    <td width=\"50%\" style=\"background:url(/Content/images/tree/Tree_Dot.gif)\"></" +
"td>\r\n                                <td width=\"3px\" height=\"3px\" ><img src=\"/Co" +
"ntent/images/tree/Tree_Dot.gif\" border=\"0\"></td>\r\n                              " +
"  <td width=\"50%\" style=\"background:url(/Content/images/tree/Tree_Empty.gif)\"></" +
"td>\r\n                            </tr>\r\n                        </tbody>\r\n      " +
"              </table>\r\n                </td>\r\n            </tr>\r\n        </scri" +
"pt>\r\n\r\n        <!--加载脚本库-->\r\n");

WriteLiteral("        ");

            
            #line 129 "..\..\Areas\Sys\Views\Organize\Index.cshtml"
   Write(Scripts.Render("~/Content/js/librarys"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <!--加载easyui加载器-->\r\n        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 7824), Tuple.Create("\"", 7940)
, Tuple.Create(Tuple.Create("", 7830), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/easyui/")
, 7830), false)
            
            #line 131 "..\..\Areas\Sys\Views\Organize\Index.cshtml"
, Tuple.Create(Tuple.Create("", 7850), Tuple.Create<System.Object, System.Int32>(AppSettings.EasyuiVersion
            
            #line default
            #line hidden
, 7850), false)
, Tuple.Create(Tuple.Create("", 7876), Tuple.Create("/easyloader.js?locale=", 7876), true)
            
            #line 131 "..\..\Areas\Sys\Views\Organize\Index.cshtml"
                                , Tuple.Create(Tuple.Create("", 7898), Tuple.Create<System.Object, System.Int32>(AppLoginer.Locale
            
            #line default
            #line hidden
, 7898), false)
, Tuple.Create(Tuple.Create("", 7916), Tuple.Create("&theme=", 7916), true)
            
            #line 131 "..\..\Areas\Sys\Views\Organize\Index.cshtml"
                                                         , Tuple.Create(Tuple.Create("", 7923), Tuple.Create<System.Object, System.Int32>(AppLoginer.Theme
            
            #line default
            #line hidden
, 7923), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("        ");

            
            #line 132 "..\..\Areas\Sys\Views\Organize\Index.cshtml"
   Write(Scripts.Render("~/Resource/Sys/Organize.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n            var data = ");

            
            #line 134 "..\..\Areas\Sys\Views\Organize\Index.cshtml"
                  Write(Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(Model)));

            
            #line default
            #line hidden
WriteLiteral(";\r\n            ko.bindingViewModel(new viewModelOranize());\r\n        </script>\r\n\r" +
"\n        <!--加载图标库CSS-->\r\n        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 8253), Tuple.Create("\"", 8287)
, Tuple.Create(Tuple.Create("", 8260), Tuple.Create<System.Object, System.Int32>(Href("~/Content/css/icon/icon.css")
, 8260), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    </body>\r\n</html>\r\n \r\n\r\n");

        }
    }
}
#pragma warning restore 1591
