#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zephyr.Web.Mvc.Views.Home
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Index()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Home\Index.cshtml"
  
    Layout = null;

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.o" +
"rg/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html");

WriteLiteral(" xmlns=\"http://www.w3.org/1999/xhtml\"");

WriteLiteral(">\r\n    <head>\r\n        <meta");

WriteLiteral(" http-equiv=\"Content-Type\"");

WriteLiteral(" content=\"text/html; charset=utf-8\"");

WriteLiteral("/>\r\n        <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n        <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width\"");

WriteLiteral(" />\r\n        <title>");

            
            #line 11 "..\..\Views\Home\Index.cshtml"
          Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 482), Tuple.Create("\"", 509)
, Tuple.Create(Tuple.Create("", 489), Tuple.Create<System.Object, System.Int32>(Href("~/Images/favicon.ico")
, 489), false)
);

WriteLiteral(" rel=\"shortcut icon\"");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(" />\r\n        <!--加载页面CSS-->\r\n");

WriteLiteral("        ");

            
            #line 14 "..\..\Views\Home\Index.cshtml"
   Write(Styles.Render("~/Content/css/index"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <!--加载控件CSS-->\r\n        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 663), Tuple.Create("\"", 752)
, Tuple.Create(Tuple.Create("", 670), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/easyui/")
, 670), false)
            
            #line 16 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 690), Tuple.Create<System.Object, System.Int32>(AppSettings.EasyuiVersion
            
            #line default
            #line hidden
, 690), false)
, Tuple.Create(Tuple.Create("", 716), Tuple.Create("/themes/", 716), true)
            
            #line 16 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 724), Tuple.Create<System.Object, System.Int32>(AppLoginer.Theme
            
            #line default
            #line hidden
, 724), false)
, Tuple.Create(Tuple.Create("", 741), Tuple.Create("/easyui.css", 741), true)
);

WriteLiteral(" rel=\"Stylesheet\"");

WriteLiteral("/>\r\n        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 787), Tuple.Create("\"", 828)
, Tuple.Create(Tuple.Create("", 794), Tuple.Create<System.Object, System.Int32>(Href("~/Content/css/btns/sexybuttons.css")
, 794), false)
);

WriteLiteral("  rel=\"Stylesheet\"");

WriteLiteral("/>\r\n        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 864), Tuple.Create("\"", 901)
, Tuple.Create(Tuple.Create("", 871), Tuple.Create<System.Object, System.Int32>(Href("~/Content/css/btns/css3btn.css")
, 871), false)
);

WriteLiteral("  rel=\"Stylesheet\"");

WriteLiteral("/>\r\n        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 937), Tuple.Create("\"", 999)
, Tuple.Create(Tuple.Create("", 944), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/jquery-plugins/showloading/showLoading.css")
, 944), false)
);

WriteLiteral("  rel=\"Stylesheet\"");

WriteLiteral("/>\r\n        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1035), Tuple.Create("\"", 1094)
, Tuple.Create(Tuple.Create("", 1042), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/jquery-plugins/ztree/3.5/zTreeStyle.css")
, 1042), false)
);

WriteLiteral("  rel=\"Stylesheet\"");

WriteLiteral("/>\r\n        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1130), Tuple.Create("\"", 1191)
, Tuple.Create(Tuple.Create("", 1137), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/jquery-plugins/jnotify/jquery.jnotify.css")
, 1137), false)
);

WriteLiteral("  rel=\"Stylesheet\"");

WriteLiteral("/>\r\n        <!--加载主题CSS-->\r\n");

WriteLiteral("        ");

            
            #line 23 "..\..\Views\Home\Index.cshtml"
   Write(StylesLess.Render("~/Content/css/theme/" + AppLoginer.Theme));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </head>\r\n    <body");

WriteLiteral(" class=\"easyui-layout\"");

WriteLiteral(" fit=\"true\"");

WriteLiteral(" scroll=\"no\"");

WriteLiteral(">\r\n        <noscript>\r\n            <div");

WriteLiteral(" class=\"noscript\"");

WriteLiteral(">\r\n                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 1455), Tuple.Create("\"", 1490)
, Tuple.Create(Tuple.Create("", 1461), Tuple.Create<System.Object, System.Int32>(Href("~/Content/images/noscript.gif")
, 1461), false)
);

WriteLiteral(" alt=\"抱歉，请开启脚本支持！\"");

WriteLiteral(" />\r\n            </div>\r\n        </noscript>\r\n\r\n");

WriteLiteral("        ");

            
            #line 32 "..\..\Views\Home\Index.cshtml"
   Write(Html.Partial("_LayoutPartial"));

            
            #line default
            #line hidden
WriteLiteral("\r\n  \r\n        <div");

WriteLiteral(" id=\"closeMenu\"");

WriteLiteral(" class=\"easyui-menu hide\"");

WriteLiteral(" style=\"width:150px;\"");

WriteLiteral(">\r\n\t\t    <div");

WriteLiteral(" id=\"refresh\"");

WriteLiteral(">刷新</div>\r\n\t\t    <div");

WriteLiteral(" class=\"menu-sep\"");

WriteLiteral("></div>\r\n\t\t    <div");

WriteLiteral(" id=\"close\"");

WriteLiteral(">关闭</div>\r\n\t\t    <div");

WriteLiteral(" id=\"closeall\"");

WriteLiteral(">全部关闭</div>\r\n\t\t    <div");

WriteLiteral(" id=\"closeother\"");

WriteLiteral(">除此之外全部关闭</div>\r\n\t\t    <div");

WriteLiteral(" class=\"menu-sep\"");

WriteLiteral("></div>\r\n\t\t    <div");

WriteLiteral(" id=\"closeright\"");

WriteLiteral(">关闭右侧标签</div>\r\n\t\t    <div");

WriteLiteral(" id=\"closeleft\"");

WriteLiteral(">关闭左侧标签</div>\r\n\t\t    <div");

WriteLiteral(" class=\"menu-sep\"");

WriteLiteral("></div>\r\n\t\t    <div");

WriteLiteral(" id=\"exit\"");

WriteLiteral(">退出</div>\r\n\t    </div>\r\n\r\n        <div");

WriteLiteral(" id=\"w\"");

WriteLiteral("></div>\r\n        <div");

WriteLiteral(" id=\"notity\"");

WriteLiteral("></div>\r\n       \r\n        <!--加载页面脚本-->\r\n");

WriteLiteral("        ");

            
            #line 51 "..\..\Views\Home\Index.cshtml"
   Write(System.Web.Optimization.Scripts.Render("~/Content/js/index"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">wrapper.initSettings(");

            
            #line 52 "..\..\Views\Home\Index.cshtml"
                                                       Write(Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(AppLoginer.GetSettings())));

            
            #line default
            #line hidden
WriteLiteral(");</script>\r\n        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 2414), Tuple.Create("\"", 2487)
, Tuple.Create(Tuple.Create("", 2420), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/easyui/")
, 2420), false)
            
            #line 53 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 2440), Tuple.Create<System.Object, System.Int32>(AppSettings.EasyuiVersion
            
            #line default
            #line hidden
, 2440), false)
, Tuple.Create(Tuple.Create("", 2466), Tuple.Create("/jquery.easyui.min.js", 2466), true)
);

WriteLiteral("></script>\r\n        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 2538), Tuple.Create("\"", 2618)
, Tuple.Create(Tuple.Create("", 2544), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/easyui/")
, 2544), false)
            
            #line 54 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 2564), Tuple.Create<System.Object, System.Int32>(AppSettings.EasyuiVersion
            
            #line default
            #line hidden
, 2564), false)
, Tuple.Create(Tuple.Create("", 2590), Tuple.Create("/locale/easyui-lang-zh_CN.js", 2590), true)
);

WriteLiteral("></script>\r\n        <!--加载图标库CSS-->\r\n        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 2669), Tuple.Create("\"", 2703)
, Tuple.Create(Tuple.Create("", 2676), Tuple.Create<System.Object, System.Int32>(Href("~/Content/css/icon/icon.css")
, 2676), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral("/>\r\n    </body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
