#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zephyr.Web.Sys.Areas.Sys.Views.Parameter
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Sys/Views/Parameter/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Index()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Areas\Sys\Views\Parameter\Index.cshtml"
  
    ViewBag.Title = "title";
    Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n        ");

WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 8 "..\..\Areas\Sys\Views\Parameter\Index.cshtml"
   Write(Scripts.Render("~/Resource/Sys/Parameter.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n            using(\'validatebox\');\r\n            ko.bindingViewModel(new viewMod" +
"el());\r\n        </script>\r\n");

});

WriteLiteral("        <div");

WriteLiteral(" class=\"z-toolbar\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" plain=\"true\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-arrow_refresh\"");

WriteLiteral(" title=\"刷新\"");

WriteLiteral(" data-bind=\"click:refreshClick\"");

WriteLiteral(">刷新</a>\r\n            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" plain=\"true\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-add\"");

WriteLiteral(" title=\"新增\"");

WriteLiteral(" data-bind=\"click:addClick\"");

WriteLiteral(">新增</a>\r\n            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" plain=\"true\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-edit\"");

WriteLiteral(" data-bind=\"click:editClick\"");

WriteLiteral(" title=\"编辑\"");

WriteLiteral(">编辑</a>\r\n            ");

WriteLiteral("\r\n            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" plain=\"true\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-save\"");

WriteLiteral(" title=\"保存\"");

WriteLiteral(" data-bind=\"click:saveClick\"");

WriteLiteral(">保存</a>\r\n        </div>\r\n \r\n        <table");

WriteLiteral(" id=\"gridlist\"");

WriteLiteral(" data-bind=\"datagrid:grid\"");

WriteLiteral(">\r\n             <thead>  \r\n                <tr>  \r\n                    <th");

WriteLiteral(" field=\"_id\"");

WriteLiteral(" hidden=\"true\"");

WriteLiteral("></th>\r\n                    <th");

WriteLiteral(" field=\"ParamCode\"");

WriteLiteral("           sortable=\"true\"");

WriteLiteral(" align=\"left\"");

WriteLiteral("    width=\"150\"");

WriteLiteral("  editor=\"{type:\'validatebox\',options:{required: true }}\"");

WriteLiteral(" >参数编码   </th>  \r\n                    <th");

WriteLiteral(" field=\"ParamValue\"");

WriteLiteral("          sortable=\"true\"");

WriteLiteral(" align=\"left\"");

WriteLiteral("    width=\"380\"");

WriteLiteral("  editor=\"text\"");

WriteLiteral(" >参数值     </th> \r\n                    <th");

WriteLiteral(" field=\"Description\"");

WriteLiteral("         sortable=\"true\"");

WriteLiteral(" align=\"left\"");

WriteLiteral("    width=\"250\"");

WriteLiteral("  editor=\"text\"");

WriteLiteral(" >描述说明   </th>  \r\n                    <th");

WriteLiteral(" field=\"IsUserEditable\"");

WriteLiteral("      sortable=\"true\"");

WriteLiteral(" align=\"center\"");

WriteLiteral("    width=\"70\"");

WriteLiteral("   formatter=\"com.formatCheckbox\"");

WriteLiteral(" >是否可编辑   </th>  \r\n                </tr>                            \r\n           " +
" </thead>      \r\n        </table> \r\n ");

        }
    }
}
#pragma warning restore 1591
