#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zephyr.Web.Mvc.Views.Login
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Login/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Index()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Login\Index.cshtml"
  
    Layout = null;

            
            #line default
            #line hidden
WriteLiteral("\r\n<!doctype html>\r\n<html>\r\n    <head>\r\n        <title>");

            
            #line 7 "..\..\Views\Login\Index.cshtml"
          Write(ViewBag.CnName);

            
            #line default
            #line hidden
WriteLiteral("-登录</title>\r\n        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 120), Tuple.Create("\"", 155)
, Tuple.Create(Tuple.Create("", 127), Tuple.Create<System.Object, System.Int32>(Href("~/Content/css/page/login.css")
, 127), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 209), Tuple.Create("\"", 277)
, Tuple.Create(Tuple.Create("", 215), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/jquery/jquery-")
, 215), false)
            
            #line 9 "..\..\Views\Login\Index.cshtml"
, Tuple.Create(Tuple.Create("", 242), Tuple.Create<System.Object, System.Int32>(AppSettings.JqueryVersion
            
            #line default
            #line hidden
, 242), false)
, Tuple.Create(Tuple.Create("", 270), Tuple.Create(".min.js", 270), true)
);

WriteLiteral("></script>\r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 305), Tuple.Create("\"", 344)
, Tuple.Create(Tuple.Create("", 311), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/library/json2.min.js")
, 311), false)
);

WriteLiteral("></script>\r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 372), Tuple.Create("\"", 442)
, Tuple.Create(Tuple.Create("", 378), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/knockout/knockout-")
, 378), false)
            
            #line 11 "..\..\Views\Login\Index.cshtml"
, Tuple.Create(Tuple.Create("", 409), Tuple.Create<System.Object, System.Int32>(AppSettings.KnockoutVersion
            
            #line default
            #line hidden
, 409), false)
, Tuple.Create(Tuple.Create("", 439), Tuple.Create(".js", 439), true)
);

WriteLiteral("></script>\r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 470), Tuple.Create("\"", 508)
, Tuple.Create(Tuple.Create("", 476), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/viewmodels/login.js")
, 476), false)
);

WriteLiteral("></script>\r\n        <script");

WriteLiteral(" src=\"http://counter.sina.com.cn/ip\"");

WriteLiteral("></script>\r\n    </head>\r\n    <body>\r\n        <div");

WriteLiteral(" class=\"second_body\"");

WriteLiteral(">\r\n            <form");

WriteLiteral(" data-bind=\"submit:loginClick\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"logo\"");

WriteLiteral("><img");

WriteLiteral(" src=\"/Content/images/login/logo.png\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(" /></div>\r\n                <div");

WriteLiteral(" class=\"title-zh\"");

WriteLiteral(" >");

            
            #line 19 "..\..\Views\Login\Index.cshtml"
                                  Write(ViewBag.CnName);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                <div");

WriteLiteral(" class=\"title-en\"");

WriteAttribute("style", Tuple.Create(" style=\"", 886), Tuple.Create("\"", 914)
            
            #line 20 "..\..\Views\Login\Index.cshtml"
, Tuple.Create(Tuple.Create("", 894), Tuple.Create<System.Object, System.Int32>(ViewBag.EnNameStyle
            
            #line default
            #line hidden
, 894), false)
);

WriteLiteral(">");

            
            #line 20 "..\..\Views\Login\Index.cshtml"
                                                              Write(ViewBag.EnName);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                <div");

WriteLiteral(" class=\"message\"");

WriteLiteral(" data-bind=\"html:message\"");

WriteLiteral("></div>\r\n                <table");

WriteLiteral(" border=\"0\"");

WriteLiteral(" style=\"width:300px;\"");

WriteLiteral(">\r\n                    <tr>\r\n                        <td");

WriteLiteral(" style=\"padding-bottom: 5px;width:55px;\"");

WriteLiteral(">用户名：</td>\r\n                        <td");

WriteLiteral(" colspan=\"2\"");

WriteLiteral("><input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"login\"");

WriteLiteral(" data-bind=\"value:form.usercode\"");

WriteLiteral(" /></td>\r\n                    </tr>\r\n                    <tr>\r\n                  " +
"      <td");

WriteLiteral(" class=\"lable\"");

WriteLiteral(" style=\"letter-spacing: 0.5em; vertical-align: middle\"");

WriteLiteral(">密码：</td>\r\n                        <td");

WriteLiteral(" colspan=\"2\"");

WriteLiteral("><input");

WriteLiteral(" type=\"password\"");

WriteLiteral(" class=\"login\"");

WriteLiteral(" data-bind=\"value:form.password\"");

WriteLiteral(" /></td>\r\n                    </tr>\r\n                    <tr>\r\n                  " +
"      <td></td>\r\n                        <td");

WriteLiteral(" colspan=\"2\"");

WriteLiteral("><input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" data-bind=\"checked:form.remember\"");

WriteLiteral(" /><span>系统记住我</span></td>\r\n                    </tr>\r\n                    <tr>\r\n" +
"                        <td");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">\r\n                            <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"登录\"");

WriteLiteral(" class=\"login_button\"");

WriteLiteral(" />\r\n                            <input");

WriteLiteral(" type=\"button\"");

WriteLiteral(" value=\"重置\"");

WriteLiteral(" class=\"reset_botton\"");

WriteLiteral(" data-bind=\"click:resetClick\"");

WriteLiteral(" />\r\n                        </td>\r\n                    </tr>\r\n                </" +
"table>\r\n            </form>\r\n        </div>\r\n    </body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
