#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zephyr.Web.Mvc.Views.Plugins
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Plugins/Lookup.cshtml")]
    public partial class Lookup : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Lookup()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Plugins\Lookup.cshtml"
  
    ViewBag.Title = "Lookup";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("head", () => {

WriteLiteral("\r\n <style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(">\r\n      .z-toolbar{ border-width:0; margin:0;}\r\n      .lbl { text-align:right; l" +
"ine-height:25px;}\r\n      .panel-body{ border-width:0 !important;}\r\n      body{ p" +
"adding:0 !important;}\r\n      #list{ height:317px;}\r\n  </style>\r\n");

});

WriteLiteral("\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        var vmodel; grid = $('#list');
        $(function () {
            $('#valueField').focus();
            using(['treegrid', 'lookup'], function () {
                vmodel = new viewModel(getOptions());
                ko.applyBindings(vmodel);
            });
        });
    </script>
");

});

WriteLiteral("    <div");

WriteLiteral(" class=\"z-toolbar\"");

WriteLiteral(" style=\"border-bottom-width:1px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" id=\"master\"");

WriteLiteral(" class=\"container_16\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"grid_2 lbl\"");

WriteLiteral(" id=\"valueTitle\"");

WriteLiteral(">编码</div>\r\n            <div");

WriteLiteral(" class=\"grid_4 val\"");

WriteLiteral("><input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"valueField\"");

WriteLiteral(" name=\"valueField\"");

WriteLiteral(" data-bind=\"value:form.value,event:{keypress:keyDown}\"");

WriteLiteral("  class=\"z-txt\"");

WriteLiteral(" data-cp=\"like\"");

WriteLiteral(" style=\"width:100%\"");

WriteLiteral("  /></div>\r\n            <div");

WriteLiteral(" class=\"grid_2 lbl\"");

WriteLiteral(" id=\"textTitle\"");

WriteLiteral(">名称</div>\r\n            <div");

WriteLiteral(" class=\"grid_4 val\"");

WriteLiteral("><input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"textField\"");

WriteLiteral(" name=\"textField\"");

WriteLiteral(" data-bind=\"value:form.text,event:{keypress:keyDown}\"");

WriteLiteral(" class=\"z-txt\"");

WriteLiteral(" data-cp=\"like\"");

WriteLiteral(" style=\"width:100%\"");

WriteLiteral("/></div>\r\n            <div");

WriteLiteral(" class=\"grid_4 val\"");

WriteLiteral(" style=\"margin-top:0px;\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" id=\"btnSearch\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" plain=\"true\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-search\"");

WriteLiteral(" title=\"查询\"");

WriteLiteral(" data-bind=\"click:searchClick\"");

WriteLiteral(">查询</a>\r\n                <a");

WriteLiteral(" id=\"btnClear\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" plain=\"true\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-clear\"");

WriteLiteral(" title=\"清空\"");

WriteLiteral(" data-bind=\"click:clearClick\"");

WriteLiteral(">清空</a>\r\n            </div>\r\n        </div>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" id=\"list\"");

WriteLiteral(" data-bind=\"treegrid:gridSetting\"");

WriteLiteral("></div>   \r\n \r\n     <div");

WriteLiteral(" style=\"text-align:center;\"");

WriteLiteral(" class=\"z-toolbar-dialog\"");

WriteLiteral(">\r\n        <a");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" data-options=\"iconCls:\'icon-ok\'\"");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral("  data-bind=\"click:confirmClick\"");

WriteLiteral(">确定</a>  \r\n        <a");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" data-options=\"iconCls:\'icon-cancel\'\"");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(" data-bind=\"click:cancelCick\"");

WriteLiteral(">取消</a> \r\n    </div>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2142), Tuple.Create("\"", 2181)
, Tuple.Create(Tuple.Create("", 2148), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/viewmodels/lookup.js")
, 2148), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n");

        }
    }
}
#pragma warning restore 1591
