#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zephyr.Web.Sys.Areas.Sys.Views.Role
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Sys/Views/Role/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Index()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Areas\Sys\Views\Role\Index.cshtml"
  
    ViewBag.Title = "title";
    Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n        ");

WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 8 "..\..\Areas\Sys\Views\Role\Index.cshtml"
   Write(Scripts.Render("~/Resource/Sys/Role.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n            using(\'validatebox\');\r\n            var data = ");

            
            #line 11 "..\..\Areas\Sys\Views\Role\Index.cshtml"
                  Write(Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(Model)));

            
            #line default
            #line hidden
WriteLiteral(@";
            ko.bindingViewModel(new viewModel(data));
            var formatterPermit = function (value, row) {
                var html = '<a href=""#"" onclick=\'permissionTab(' + JSON.stringify(row) + ')\'><span class=""icon icon-set1"">&nbsp;</span>[编辑权限]</a>';
                html += '<a href=""#"" onclick=\'memberDialog(' + JSON.stringify(row) + ')\' style=""margin-left:10px""><span class=""icon icon-users "">&nbsp;</span>[管理成员]</a>';
                return html;
            };
        </script>
");

});

WriteLiteral("        <div");

WriteLiteral(" class=\"z-toolbar\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" id=\"a_refresh\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" plain=\"true\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-arrow_refresh\"");

WriteLiteral(" title=\"刷新\"");

WriteLiteral(" data-bind=\"click:refreshClick\"");

WriteLiteral(">刷新</a>\r\n            <a");

WriteLiteral(" id=\"a_add\"");

WriteLiteral("    href=\"#\"");

WriteLiteral(" plain=\"true\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-add\"");

WriteLiteral(" title=\"新增\"");

WriteLiteral(" data-bind=\"click:addClick\"");

WriteLiteral(">新增</a>\r\n            <a");

WriteLiteral(" id=\"a_edit\"");

WriteLiteral("   href=\"#\"");

WriteLiteral(" plain=\"true\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-edit\"");

WriteLiteral(" data-bind=\"click:editClick\"");

WriteLiteral(" title=\"编辑\"");

WriteLiteral(">编辑</a>\r\n            <a");

WriteLiteral(" id=\"a_del\"");

WriteLiteral("    href=\"#\"");

WriteLiteral(" plain=\"true\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-cross\"");

WriteLiteral(" title=\"删除\"");

WriteLiteral(" data-bind=\"click:deleteClick\"");

WriteLiteral(">删除</a>\r\n            <a");

WriteLiteral(" id=\"a_save\"");

WriteLiteral("  href=\"#\"");

WriteLiteral(" plain=\"true\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-save\"");

WriteLiteral(" data-bind=\"click:saveClick\"");

WriteLiteral(" title=\"保存\"");

WriteLiteral(">保存</a>\r\n        </div>\r\n        \r\n        <table");

WriteLiteral(" id=\"gridlist\"");

WriteLiteral(" data-bind=\"datagrid:grid\"");

WriteLiteral(">\r\n             <thead>  \r\n                <tr>  \r\n                    <th");

WriteLiteral(" field=\"_id\"");

WriteLiteral("  hidden=\"true\"");

WriteLiteral("></th>  \r\n                    <th");

WriteLiteral(" field=\"RoleName\"");

WriteLiteral("    align=\"left\"");

WriteLiteral("    width=\"150\"");

WriteLiteral(" editor=\"{type:\'validatebox\',options:{required: true }}\"");

WriteLiteral(">角色名称</th>  \r\n                    <th");

WriteLiteral(" field=\"RoleCode\"");

WriteLiteral("    align=\"left\"");

WriteLiteral("    width=\"100\"");

WriteLiteral("  editor=\"{type:\'validatebox\',options:{required: true }}\"");

WriteLiteral(">角色编码   </th>  \r\n                    <th");

WriteLiteral(" field=\"RoleSeq\"");

WriteLiteral("     align=\"left\"");

WriteLiteral("    width=\"100\"");

WriteLiteral(" editor=\"text\"");

WriteLiteral(" >排序   </th>\r\n                    <th");

WriteLiteral(" field=\"Description\"");

WriteLiteral(" align=\"left\"");

WriteLiteral("    width=\"200\"");

WriteLiteral(" editor=\"text\"");

WriteLiteral(">描述     </th> \r\n                    <th");

WriteLiteral(" field=\"Permit\"");

WriteLiteral(" align=\"center\"");

WriteLiteral("    width=\"200\"");

WriteLiteral(" formatter=\"formatterPermit\"");

WriteLiteral(">操作     </th> \r\n                </tr>                            \r\n            </" +
"thead>      \r\n        </table> \r\n\r\n<script");

WriteLiteral(" type=\"text/html\"");

WriteLiteral(" id=\"members-template\"");

WriteLiteral(">\r\n    <div style=\"margin:5px;\">\r\n        <div style=\"border-bottom:1px solid #CC" +
"C; margin-bottom:5px;\">\r\n            <span id=\"role_name\" class=\"icon32 icon-gro" +
"up32\" style=\"padding-left:48px;font-weight:bold; font-size:14px;color:#666;\" dat" +
"a-bind=\"text:RoleName\">角色名称</span> \r\n        </div>\r\n        <div style=\"margin-" +
"bottom:10px;height:20px;\">\r\n            <label>描述：</label><input data-bind=\"valu" +
"e:Description\" type=\"text\" readonly=true class=\"z-txt\" style=\"width:430px;color:" +
"#666;vertical-align:middle\">\r\n        </div>\r\n        <div> 成员：</div>\r\n        <" +
"select id=\"user_groups\" data-bind=\"options:members,optionsText:memberText ,value" +
":selectValue\" size=\"10\" style=\"width:475px; line-height:30px;height:195px;paddin" +
"g:5px\"></select>\r\n        <div style=\"margin-top:2px;\"><a href=\"#\" id=\"group_add" +
"\" class=\"easyui-linkbutton\" plain=\"true\" iconCls=\"icon-group-add\" data-bind=\"cli" +
"ck:addClick\">添加</a>\r\n            <a href=\"#\" class=\"easyui-linkbutton\" id=\"group" +
"_delete\" plain=\"true\" iconcls=\"icon-group-delete\" data-bind=\"click:deleteClick\">" +
"删除</a>\r\n            <a href=\"#\" class=\"easyui-linkbutton\" id=\"group_clear\" plain" +
"=\"true\" iconCls=\"icon-clear\" data-bind=\"click:clearClick\">清空</a>\r\n        </div>" +
"\r\n    </div>\r\n    <div style=\"text-align:center;\">\r\n        <a class=\"easyui-lin" +
"kbutton\" data-options=\"iconCls:\'icon-ok\'\" data-bind=\"click:confirmClick\" href=\"j" +
"avascript:void(0)\"  >确定</a>  \r\n        <a class=\"easyui-linkbutton\" data-options" +
"=\"iconCls:\'icon-cancel\'\" data-bind=\"click:cancelClick\" href=\"javascript:void(0)\"" +
">取消</a> \r\n    </div>\r\n</script>\r\n\r\n<script");

WriteLiteral(" type=\"text/html\"");

WriteLiteral(" id=\"choose-members-template\"");

WriteLiteral(">\r\n    <div style=\"margin:5px;height:425px;overflow:auto;\">\r\n         <div style=" +
"\"border-bottom:1px solid #CCC; margin-bottom:5px;\">\r\n            <span class=\"ic" +
"on32 icon-org32\" style=\"padding-left:48px;font-weight:bold; font-size:14px;color" +
":#666;\">\r\n            机构成员<input type=\"checkbox\" style=\"vertical-align:middle;ma" +
"rgin-left:5px;\" data-bind=\"checked:checkAllOrganize\"/>全选</span> \r\n        </div>" +
"\r\n\r\n        <ul style=\"margin:0;padding:0;clear:both\" data-bind=\"foreach:organiz" +
"es\">\r\n            <li style=\"float:left;list-style:none;margin:3px;\"><input type" +
"=\"checkbox\" data-bind=\"value:OrganizeCode,checked:Checked\" style=\"vertical-align" +
":middle\" /><label data-bind=\"text:OrganizeName\" ></label></li>\r\n        </ul>\r\n\r" +
"\n        <div style=\"border-bottom:1px solid #CCC; margin-bottom:5px;clear:both\"" +
">\r\n            <span class=\"icon32 icon-user32\" style=\"padding-left:48px;font-we" +
"ight:bold; font-size:14px;color:#666;\">\r\n            用户成员<input type=\"checkbox\" " +
"style=\"vertical-align:middle;margin-left:5px;\" data-bind=\"checked:checkAllUser\"/" +
">全选</span> \r\n        </div>\r\n\r\n        <ul style=\"margin:0;padding:0;clear:both\"" +
" data-bind=\"foreach:users\">\r\n            <li style=\"float:left;list-style:none;m" +
"argin:3px;\"><input type=\"checkbox\" data-bind=\"value:UserCode,checked:Checked\" st" +
"yle=\"vertical-align:middle\"/><label data-bind=\"text:UserName\"></label></li>\r\n   " +
"     </ul>\r\n    </div>\r\n    <div style=\"text-align:center;clear:both\">\r\n        " +
"<a class=\"easyui-linkbutton\" data-options=\"iconCls:\'icon-ok\'\" data-bind=\"click:c" +
"onfirmClick\" href=\"javascript:void(0)\"  >确定</a>  \r\n        <a class=\"easyui-link" +
"button\" data-options=\"iconCls:\'icon-cancel\'\" data-bind=\"click:cancelClick\" href=" +
"\"javascript:void(0)\">取消</a> \r\n    </div>\r\n</script>\r\n\r\n<script");

WriteLiteral(" type=\"text/html\"");

WriteLiteral(" id=\"permission-template\"");

WriteLiteral(">\r\n    <div class=\"container\" style=\"margin:5px;height:525px;\">\r\n        <div>\r\n " +
"           <span class=\"icon32 icon-group32\" style=\"padding-left:48px;font-weigh" +
"t:bold; font-size:14px;color:#666;\" data-bind=\"text:role.RoleName\">角色名称</span> \r" +
"\n            <span data-bind=\"text:role.Description\" style=\"margin-left:10px;\"><" +
"/span>\r\n        </div>\r\n \r\n        <div class=\"easyui-tabs\" data-bind=\"easyuiTab" +
"s:tab\">  \r\n            <div title=\"菜单权限\" >\r\n                <table id=\"gridlist\"" +
" data-bind=\"treegrid:grid\">\r\n                    <thead>  \r\n                    " +
"    <tr>  \r\n                            <th field=\"chk\" checkbox=\"true\"></th>\r\n " +
"                           <th field=\"MenuName\"    align=\"left\"    width=\"150\">菜" +
"单   </th>  \r\n                            <th field=\"MenuCode\"    align=\"left\"   " +
" width=\"80\" >编码   </th>  \r\n                            <th field=\"Description\" a" +
"lign=\"left\"    width=\"200\" >备注说明   </th>  \r\n                        </tr>       " +
"                     \r\n                    </thead>      \r\n                </tab" +
"le>   \r\n            </div>\r\n\r\n            <div title=\"按钮权限\">\r\n                <t" +
"able data-bind=\"treegrid:grid2\"></table>   \r\n            </div>\r\n\r\n            <" +
"div title=\"数据权限\" >\r\n                 <table data-bind=\"treegrid:grid3\"></table> " +
"\r\n            </div> \r\n\r\n            <div title=\"字段权限\" >\r\n                 <tabl" +
"e data-bind=\"treegrid:grid4\"></table> \r\n            </div> \r\n        </div> \r\n  " +
"  </div> \r\n    <div style=\"text-align:center;clear:both\">\r\n        <a class=\"eas" +
"yui-linkbutton\" data-options=\"iconCls:\'icon-ok\'\" data-bind=\"click:confirmClick\" " +
"href=\"javascript:void(0)\"  >确定</a>  \r\n        <a class=\"easyui-linkbutton\" data-" +
"options=\"iconCls:\'icon-cancel\'\" data-bind=\"click:cancelClick\" href=\"javascript:v" +
"oid(0)\">取消</a> \r\n    </div>\r\n</script>");

        }
    }
}
#pragma warning restore 1591
