#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zephyr.Web.Sys.Areas.Sys.Views.Generator
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Sys/Views/Generator/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Index()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Areas\Sys\Views\Generator\Index.cshtml"
  
    ViewBag.Title = "代码生成";
    Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("head", () => {

WriteLiteral("\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 110), Tuple.Create("\"", 172)
, Tuple.Create(Tuple.Create("", 117), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/jquery-plugins/smartwizard/smart_wizard.css")
, 117), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(@">
        div#navigation{float: left;width: 180px;}
        div#wrapper{float: right;width: 100%;margin-left: -185px;}
        div#wizard{margin-left: 185px;}
        ul.anchor{margin:0 0 10px 0 !important;}
        ul li{margin-left:-16px;}
        .grid .z-txt{margin:0 -3px;width:90%;} 
        .grid input{width:90%;}
        .grid input[type=checkbox]{cursor:default;}
        .grid select{width:80%;padding:0 !important;height:22px;}
        .grid select + a{margin:5px;}
       
        .tDnD_whileDrag{background-color: #FBEC88 !important;}
    </style>
");

});

WriteLiteral("\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 832), Tuple.Create("\"", 898)
, Tuple.Create(Tuple.Create("", 838), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/jquery-plugins/smartwizard/jquery.smartWizard.js")
, 838), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 922), Tuple.Create("\"", 973)
, Tuple.Create(Tuple.Create("", 928), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/jquery-extend/jquery.tablednd.js")
, 928), false)
);

WriteLiteral("></script>\r\n    ");

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 28 "..\..\Areas\Sys\Views\Generator\Index.cshtml"
Write(Scripts.Render("~/Resource/Sys/Generator.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        $(function () {\r\n            ko.applyBindings(new viewModel());\r\n     " +
"   });\r\n    </script>\r\n");

});

WriteLiteral("\r\n<div");

WriteLiteral(" id=\"container\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" id=\"navigation\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"panel-header\"");

WriteLiteral(" style=\"width: 168px; border-width: 0; background: #FAFAFA;\"");

WriteLiteral(">\r\n            代码类别 \r\n            <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"z-txt\"");

WriteLiteral(" data-bind=\"easyuiCombobox:codetype\"");

WriteLiteral(" />\r\n            <div");

WriteLiteral(" style=\"margin:1px;\"");

WriteLiteral("></div>\r\n            数据库名 \r\n            <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"z-txt\"");

WriteLiteral(" data-bind=\"easyuiCombobox:database\"");

WriteLiteral(" />\r\n\r\n            <div");

WriteLiteral(" style=\"margin:5px;\"");

WriteLiteral("></div>\r\n             <div");

WriteLiteral("  data-bind=\"autoheight:60\"");

WriteLiteral("  style=\"width: 172px; border-width: 0;margin:0;padding:0; background: #FAFAFA; o" +
"verflow:auto;\"");

WriteLiteral(">\r\n                <ul");

WriteLiteral(" data-bind=\"easyuiTree:tabletree\"");

WriteLiteral("></ul>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" id=\"wrapper\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" id=\"wizard\"");

WriteLiteral(" class=\"swMain\"");

WriteLiteral(" style=\"width:100%\"");

WriteLiteral("></div>\r\n    </div>\r\n</div>\r\n\r\n<script");

WriteLiteral(" id=\"template-searchEdit\"");

WriteLiteral(" type=\"text/html\"");

WriteLiteral(@">
    <ul>
        <li><a href=""#step-1"">
            <label class=""stepNumber"">1</label>
            <span class=""stepDesc"">设置条件部<br />
                <small>定义查询条件</small>
            </span>
        </a></li>
        <li><a href=""#step-2"">
            <label class=""stepNumber"">2</label>
            <span class=""stepDesc"">设置数据列<br />
                <small>定义查询显示的数据字段</small>
            </span>
        </a></li>
        <li><a href=""#step-3"">
            <label class=""stepNumber"">3</label>
            <span class=""stepDesc"">其它设置<br />
                <small>修改其它代码生成设置</small>
            </span>
        </a></li>
    </ul>

    <div id=""step-1"" class=""step"">
        <h2 class=""StepTitle"">第一步 请勾选要查询的字段</h2>
        <div>  
            <div style=""width:200px;float:left;overflow:auto;"" data-bind=""autoheight:172"">
                    <ul data-bind=""easyuiTree:searchEdit.columntree""></ul>
            </div>  
            <div style=""float:left;overflow:auto"" data-bind=""autoheight:172,autowidth:405"">
                <table class=""grid"">
                    <thead>
                        <tr>
				            <th style=""width:50px"">字段</th>
                            <th style=""width:120px"">显示名称</th>
                            <th style=""width:120px"">控件类型</th>
				            ");

WriteLiteral(@"
                            <th style=""width:80px"">查询逻辑</th>
                        </tr>
                    </thead>
                    <tbody data-bind=""foreach:form.conditions"">
                        <tr data-bind=""attr:{id:$index}"">
                            <td data-bind=""text:field"" style=""text-align:left""></td>
                            <td><input type=""text"" class=""z-txt"" data-bind=""value:title""/></td>
                            <td><select class=""z-txt""  data-bind=""options:$root.data.input,value:type""></select></td>
                            ");

WriteLiteral("\r\n                            <td><select class=\"z-txt\"  data-bind=\"options:$root" +
".data.compare,value:cp\"></select></td>\r\n                        </tr>\r\n\r\n       " +
"             </tbody>\r\n                </table>\r\n            </div>  \r\n        <" +
"/div>\r\n    </div>\r\n    <div id=\"step-2\" class=\"step\">\r\n        <h2 class=\"StepTi" +
"tle\">第二步 请勾选要显示的数据字段</h2>\r\n        <div style=\"width:200px;float:left;overflow:a" +
"uto;\" data-bind=\"autoheight:172\">\r\n            <ul data-bind=\"easyuiTree:searchE" +
"dit.columntree2\"></ul>\r\n        </div>  \r\n        <div style=\"float:left;overflo" +
"w:auto\" data-bind=\"autoheight:172,autowidth:405\">\r\n            <table class=\"gri" +
"d\">\r\n                <thead>\r\n                    <tr>\r\n\t\t\t\t        <th style=\"w" +
"idth:50px\">字段</th>\r\n                        <th style=\"width:100px\">题头</th>\r\n   " +
"                     <th style=\"width:30px\">隐藏</th>\r\n                        <th" +
" style=\"width:30px\">排序</th>\r\n                        <th style=\"width:50px\">对齐</" +
"th>\r\n                        <th style=\"width:40px\">宽度</th>\r\n                   " +
"     <th style=\"width:50px\">格式化</th>\r\n                        <th style=\"width:5" +
"0px\">编辑器</th>\r\n                    </tr>\r\n                </thead>\r\n            " +
"    <tbody data-bind=\"foreach:form.columns\">\r\n                    <tr data-bind=" +
"\"attr:{id:$index}\">\r\n                        <td data-bind=\"text:field\" style=\"t" +
"ext-align:left\"></td>\r\n                        <td><input type=\"text\" class=\"z-t" +
"xt\" data-bind=\"value:title\" /></td>\r\n                        <td><input type=\"ch" +
"eckbox\" data-bind=\"checked:hidden\"/></td>\r\n                        <td><input ty" +
"pe=\"checkbox\" data-bind=\"checked:sortable\"/></td>\r\n                        <td><" +
"select class=\"z-txt\"  data-bind=\"options:$root.data.align,value:align\" ></select" +
"></td>\r\n                        <td><input type=\"text\" class=\"z-txt\" data-bind=\"" +
"value:width\" /></td>\r\n                        <td><select class=\"z-txt\"  data-bi" +
"nd=\"options:$root.data.formatter,optionsText:\'text\',optionsValue:\'value\',value:f" +
"ormatter\" ></select></td>\r\n                        <td><select class=\"z-txt\"  da" +
"ta-bind=\"options:$root.data.editor,optionsText:\'text\',optionsValue:\'value\',value" +
":editor\" ></select></td>\r\n                    </tr>\r\n                </tbody>\r\n " +
"           </table>\r\n        </div>  \r\n    </div>\r\n\r\n     <div id=\"step-3\" class" +
"=\"step\">\r\n        <h2 class=\"StepTitle\">第三步 其它设置</h2>\r\n\r\n        <div class=\"con" +
"tainer_12\">\r\n            <div class=\"grid_1 lbl\">业务区域</div>\r\n            <div cl" +
"ass=\"grid_2 val\"><input type=\"text\" class=\"z-txt\" data-bind=\"value:form.area\"/><" +
"/div>\r\n\r\n            <div class=\"clear\"></div>\r\n\r\n            <div class=\"grid_1" +
" lbl\">控制器名称</div>\r\n            <div class=\"grid_2 val\"><input type=\"text\" class=" +
"\"z-txt\" data-bind=\"value:form.controller\"/></div>\r\n\r\n            <div class=\"cle" +
"ar\"></div>\r\n\r\n            <div class=\"grid_1 lbl\">生成路径</div>\r\n            <div c" +
"lass=\"grid_2 val\"><input type=\"text\" class=\"z-txt\" data-bind=\"value:form.path\"/>" +
"</div>\r\n        </div>\r\n    </div>\r\n</script>\r\n\r\n<script");

WriteLiteral(" id=\"template-search\"");

WriteLiteral(" type=\"text/html\"");

WriteLiteral(@">
    <ul>
        <li><a href=""#step-1"">
            <label class=""stepNumber"">1</label>
            <span class=""stepDesc"">设置条件部<br />
                <small>定义查询条件</small>
            </span>
        </a></li>
        <li><a href=""#step-2"">
            <label class=""stepNumber"">2</label>
            <span class=""stepDesc"">设置数据列<br />
                <small>定义查询显示的数据字段</small>
            </span>
        </a></li>
        <li><a href=""#step-3"">
            <label class=""stepNumber"">3</label>
            <span class=""stepDesc"">其它设置<br />
                <small>修改其它代码生成设置</small>
            </span>
        </a></li>
    </ul>

    <div id=""step-1"" class=""step"">
        <h2 class=""StepTitle"">第一步 请勾选要查询的字段</h2>
        <div>  
            <div style=""width:200px;float:left;overflow:auto;"" data-bind=""autoheight:172"">
                    <ul data-bind=""easyuiTree:searchEdit.columntree""></ul>
            </div>  
            <div style=""float:left;overflow:auto"" data-bind=""autoheight:172,autowidth:405"">
                <table class=""grid"">
                    <thead>
                        <tr>
				            <th style=""width:50px"">字段</th>
                            <th style=""width:120px"">显示名称</th>
                            <th style=""width:120px"">控件类型</th>
				            ");

WriteLiteral(@"
                            <th style=""width:80px"">查询逻辑</th>
                        </tr>
                    </thead>
                    <tbody data-bind=""foreach:form.conditions"">
                        <tr data-bind=""attr:{id:$index}"">
                            <td data-bind=""text:field"" style=""text-align:left""></td>
                            <td><input type=""text"" class=""z-txt"" data-bind=""value:title""/></td>
                            <td><select class=""z-txt""  data-bind=""options:$root.data.input,value:type""></select></td>
                            ");

WriteLiteral("\r\n                            <td><select class=\"z-txt\"  data-bind=\"options:$root" +
".data.compare,value:cp\"></select></td>\r\n                        </tr>\r\n\r\n       " +
"             </tbody>\r\n                </table>\r\n            </div>  \r\n        <" +
"/div>\r\n    </div>\r\n    <div id=\"step-2\" class=\"step\">\r\n        <h2 class=\"StepTi" +
"tle\">第二步 请勾选要显示的数据字段</h2>\r\n        <div style=\"width:200px;float:left;overflow:a" +
"uto;\" data-bind=\"autoheight:172\">\r\n            <ul data-bind=\"easyuiTree:searchE" +
"dit.columntree2\"></ul>\r\n        </div>  \r\n        <div style=\"float:left;overflo" +
"w:auto\" data-bind=\"autoheight:172,autowidth:405\">\r\n            <table class=\"gri" +
"d\">\r\n                <thead>\r\n                    <tr>\r\n\t\t\t\t        <th style=\"w" +
"idth:50px\">字段</th>\r\n                        <th style=\"width:100px\">题头</th>\r\n   " +
"                     <th style=\"width:30px\">隐藏</th>\r\n                        <th" +
" style=\"width:30px\">排序</th>\r\n                        <th style=\"width:50px\">对齐</" +
"th>\r\n                        <th style=\"width:40px\">宽度</th>\r\n                   " +
"     <th style=\"width:50px\">格式化</th>\r\n                    </tr>\r\n               " +
" </thead>\r\n                <tbody data-bind=\"foreach:form.columns\">\r\n           " +
"         <tr data-bind=\"attr:{id:$index}\">\r\n                        <td data-bin" +
"d=\"text:field\" style=\"text-align:left\"></td>\r\n                        <td><input" +
" type=\"text\" class=\"z-txt\" data-bind=\"value:title\" /></td>\r\n                    " +
"    <td><input type=\"checkbox\" data-bind=\"checked:hidden\"/></td>\r\n              " +
"          <td><input type=\"checkbox\" data-bind=\"checked:sortable\"/></td>\r\n      " +
"                  <td><select class=\"z-txt\"  data-bind=\"options:$root.data.align" +
",value:align\" ></select></td>\r\n                        <td><input type=\"text\" cl" +
"ass=\"z-txt\" data-bind=\"value:width\" /></td>\r\n                        <td><select" +
" class=\"z-txt\"  data-bind=\"options:$root.data.formatter,optionsText:\'text\',optio" +
"nsValue:\'value\',value:formatter\" ></select></td>\r\n                    </tr>\r\n   " +
"             </tbody>\r\n            </table>\r\n        </div>  \r\n    </div>\r\n\r\n   " +
"  <div id=\"step-3\" class=\"step\">\r\n        <h2 class=\"StepTitle\">第三步 其它设置</h2>\r\n\r" +
"\n        <div class=\"container_12\">\r\n            <div class=\"grid_1 lbl\">业务区域</d" +
"iv>\r\n            <div class=\"grid_2 val\"><input type=\"text\" class=\"z-txt\" data-b" +
"ind=\"value:form.area\"/></div>\r\n\r\n            <div class=\"clear\"></div>\r\n\r\n      " +
"      <div class=\"grid_1 lbl\">控制器名称</div>\r\n            <div class=\"grid_2 val\"><" +
"input type=\"text\" class=\"z-txt\" data-bind=\"value:form.controller\"/></div>\r\n\r\n   " +
"         <div class=\"clear\"></div>\r\n\r\n            <div class=\"grid_1 lbl\">生成路径</" +
"div>\r\n            <div class=\"grid_2 val\"><input type=\"text\" class=\"z-txt\" data-" +
"bind=\"value:form.path\"/></div>\r\n        </div>\r\n    </div>\r\n</script>\r\n\r\n<script" +
"");

WriteLiteral(" id=\"template-edit\"");

WriteLiteral(" type=\"text/html\"");

WriteLiteral(">\r\n    <ul>\r\n        <li><a href=\"#step-1\">\r\n            <label class=\"stepNumber" +
"\">1</label>\r\n            <span class=\"stepDesc\">设置主表编辑区<br />\r\n                <" +
"small>定义主表编辑字段</small>\r\n            </span>\r\n        </a></li>\r\n        <li><a h" +
"ref=\"#step-2\">\r\n            <label class=\"stepNumber\">2</label>\r\n            <sp" +
"an class=\"stepDesc\">设置明细数据页签<br />\r\n                <small>定义明细表及页签</small>\r\n   " +
"         </span>\r\n        </a></li>\r\n        <li><a href=\"#step-3\">\r\n           " +
" <label class=\"stepNumber\">3</label>\r\n            <span class=\"stepDesc\">其它设置<br" +
" />\r\n                <small>修改其它代码生成设置</small>\r\n            </span>\r\n        </a" +
"></li>\r\n    </ul>\r\n\r\n    <div id=\"step-1\" class=\"step\">\r\n        <h2 class=\"Step" +
"Title\">第一步 请勾选要编辑的字段</h2>\r\n        <div>  \r\n            <div style=\"width:200px;" +
"float:left;overflow:auto;\" data-bind=\"autoheight:172\">\r\n                    <ul " +
"data-bind=\"easyuiTree:searchEdit.columntree\"></ul>\r\n            </div>  \r\n      " +
"      <div style=\"float:left;overflow:auto\" data-bind=\"autoheight:172,autowidth:" +
"405\">\r\n                <table class=\"grid\">\r\n                    <thead>\r\n      " +
"                  <tr>\r\n\t\t\t\t            <th style=\"width:20%\">字段</th>\r\n         " +
"                   <th style=\"width:40%\">标签名称</th>\r\n                            " +
"<th style=\"width:30%\">控件类型</th>\r\n                            <th style=\"width:10" +
"%\">只读</th>\r\n                        </tr>\r\n                    </thead>\r\n       " +
"             <tbody data-bind=\"foreach:form.conditions\">\r\n                      " +
"  <tr data-bind=\"attr:{id:$index}\">\r\n                            <td data-bind=\"" +
"text:field\" style=\"text-align:left\"></td>\r\n                            <td><inpu" +
"t type=\"text\" class=\"z-txt\" data-bind=\"value:title\"/></td>\r\n                    " +
"        <td><select class=\"z-txt\"  data-bind=\"options:$root.data.input,value:typ" +
"e\" style=\"width:60%\"></select><a href=\"#\">高级</a></td>\r\n                         " +
"   <td><input type=\"checkbox\" data-bind=\"checked:readonly\"/></td>\r\n             " +
"           </tr>\r\n                    </tbody>\r\n                </table>\r\n      " +
"      </div>  \r\n        </div>\r\n    </div>\r\n    <div id=\"step-2\" class=\"step\">\r\n" +
"        <h2 class=\"StepTitle\">第二步 请设置页面中的tab页签</h2>\r\n         \r\n        <div sty" +
"le=\"float:left;overflow:auto;width:150px;\" data-bind=\"autoheight:172\">\r\n        " +
"    <a href=\"#\" class=\"buttonNext\" style=\"float:left;margin:5px 3px 5px 0\" data-" +
"bind=\"click:edit.addTab\">添加Tab页签</a>\r\n            <table class=\"grid\">\r\n        " +
"        <thead>\r\n                    <tr>\r\n                        <th style=\"wi" +
"dth:30%\">#</th>\r\n                        <th style=\"width:70%\">名称</th>\r\n        " +
"            </tr>\r\n                </thead>\r\n                <tbody data-bind=\"f" +
"oreach:form.tabs\">\r\n                    <tr data-bind=\"attr:{id:$index}\">\r\n     " +
"                   <td><a href=\"#\" data-bind=\"click:$parent.edit.removeTab\">删除</" +
"a></td>\r\n                        <td><input type=\"text\" class=\"z-txt\" data-bind=" +
"\"value:title,click:$parent.edit.clickTab\" style=\"width:90%\"/></td>\r\n            " +
"        </tr>\r\n                </tbody>\r\n            </table>\r\n        </div>  \r" +
"\n\r\n         <div id=\"edit-tab-setting\" style=\"float:left;overflow:auto;\" data-bi" +
"nd=\"autoheight:172,autowidth:355,visible:edit.selectedTitle()!=null\">\r\n \r\n      " +
"  </div> \r\n    </div>\r\n\r\n     <div id=\"step-3\" class=\"step\">\r\n        <h2 class=" +
"\"StepTitle\">第三步 其它设置</h2>\r\n\r\n        <div class=\"container_12\">\r\n            <di" +
"v class=\"grid_1 lbl\">业务区域</div>\r\n            <div class=\"grid_2 val\"><input type" +
"=\"text\" class=\"z-txt\" data-bind=\"value:form.area\"/></div>\r\n\r\n            <div cl" +
"ass=\"clear\"></div>\r\n\r\n            <div class=\"grid_1 lbl\">控制器名称</div>\r\n         " +
"   <div class=\"grid_2 val\"><input type=\"text\" class=\"z-txt\" data-bind=\"value:for" +
"m.controller\"/></div>\r\n\r\n            <div class=\"clear\"></div>\r\n\r\n            <d" +
"iv class=\"grid_1 lbl\">生成路径</div>\r\n            <div class=\"grid_2 val\"><input typ" +
"e=\"text\" class=\"z-txt\" data-bind=\"value:form.path\"/></div>\r\n        </div>\r\n    " +
"</div>\r\n</script>\r\n\r\n<script");

WriteLiteral(" type=\"text/html\"");

WriteLiteral(" id=\"template-edit-tab-setting\"");

WriteLiteral(">\r\n     <div style=\"padding:8px;clear:both\">\r\n        <span>页签类型 </span>\r\n       " +
" <select class=\"z-txt\" style=\"padding:0;height:22px;\" data-bind=\"value:edit.sele" +
"ctedTab.type\">\r\n            <option value=\"empty\">empty</option>\r\n            <o" +
"ption value=\"grid\">grid</option>\r\n            <option value=\"form\">form</option>" +
"\r\n        </select> \r\n\r\n        <span data-bind=\"visible:edit.selectedTab.type()" +
"!=\'empty\'\"> 数据表 </span>\r\n        <select class=\"z-txt\" style=\"padding:0;height:2" +
"2px;\" data-bind=\"options:data.table,optionsText:\'text\',optionsValue:\'id\',value:e" +
"dit.selectedTab.subtable,visible:edit.selectedTab.type()!=\'empty\'\"></select>\r\n\r\n" +
"        <span data-bind=\"visible:edit.selectedTab.type()!=\'empty\'\">与主表的关联</span>" +
"\r\n        <select class=\"z-txt\" style=\"padding:0;height:22px;\" data-bind=\"option" +
"s:data.tablekey,value:edit.selectedTab.relationship,visible:edit.selectedTab.typ" +
"e()!=\'empty\'\"></select>\r\n    </div>\r\n\r\n    <div style=\"width:180px;float:left;ov" +
"erflow:auto;margin-right:-18px;\" data-bind=\"autoheight:212,visible:edit.selected" +
"Tab.type()!=\'empty\'\">\r\n        <ul data-bind=\"easyuiTree:edit.columntree2\"></ul>" +
"\r\n    </div> \r\n    \r\n    <div style=\"float:right;overflow:auto;\" data-bind=\"auto" +
"height:210,autowidth:535,visible:edit.selectedTab.type()!=\'empty\'\">\r\n        <ta" +
"ble class=\"grid\">\r\n            <thead>\r\n                <tr>\r\n\t\t\t\t    <th style=" +
"\"width:50px\">字段</th>\r\n                    <th style=\"width:100px\">题头</th>\r\n     " +
"               <th style=\"width:30px\" data-bind=\"visible:edit.selectedTab.type()" +
"==\'grid\'\">隐藏</th>\r\n                    <th style=\"width:30px\" data-bind=\"visible" +
":edit.selectedTab.type()==\'grid\'\">排序</th>\r\n                    <th style=\"width:" +
"50px\" data-bind=\"visible:edit.selectedTab.type()==\'grid\'\">对齐</th>\r\n             " +
"       <th style=\"width:40px\" data-bind=\"visible:edit.selectedTab.type()==\'grid\'" +
"\">宽度</th>\r\n                    <th style=\"width:50px\" data-bind=\"visible:edit.se" +
"lectedTab.type()==\'grid\'\">格式化</th>\r\n                    <th style=\"width:50px\" d" +
"ata-bind=\"visible:edit.selectedTab.type()==\'grid\'\">编辑器</th>\r\n                   " +
" <th style=\"width:50px\" data-bind=\"visible:edit.selectedTab.type()==\'form\'\">控件类型" +
"</th>\r\n                    <th style=\"width:10px\" data-bind=\"visible:edit.select" +
"edTab.type()==\'form\'\">只读</th>\r\n                </tr>\r\n            </thead>\r\n    " +
"        <tbody data-bind=\"foreach:edit.selectedTab.columns\">\r\n                <t" +
"r data-bind=\"attr:{id:$index}\">\r\n                    <td data-bind=\"text:field\" " +
"style=\"text-align:left\"></td>\r\n                    <td><input type=\"text\" class=" +
"\"z-txt\" data-bind=\"value:title\" /></td>\r\n                    <td data-bind=\"visi" +
"ble:$parent.edit.selectedTab.type()==\'grid\'\"><input type=\"checkbox\" data-bind=\"c" +
"hecked:hidden\"/></td>\r\n                    <td data-bind=\"visible:$parent.edit.s" +
"electedTab.type()==\'grid\'\"><input type=\"checkbox\" data-bind=\"checked:sortable\"/>" +
"</td>\r\n                    <td data-bind=\"visible:$parent.edit.selectedTab.type(" +
")==\'grid\'\"><select class=\"z-txt\"  data-bind=\"options:$root.data.align,value:alig" +
"n\" ></select></td>\r\n                    <td data-bind=\"visible:$parent.edit.sele" +
"ctedTab.type()==\'grid\'\"><input type=\"text\" class=\"z-txt\" data-bind=\"value:width\"" +
" /></td>\r\n                    <td data-bind=\"visible:$parent.edit.selectedTab.ty" +
"pe()==\'grid\'\"><select class=\"z-txt\"  data-bind=\"options:$root.data.formatter,opt" +
"ionsText:\'text\',optionsValue:\'value\',value:formatter\" ></select></td>\r\n         " +
"           <td data-bind=\"visible:$parent.edit.selectedTab.type()==\'grid\'\"><sele" +
"ct class=\"z-txt\"  data-bind=\"options:$root.data.editor,optionsText:\'text\',option" +
"sValue:\'value\',value:editor\" ></select></td>\r\n                    <td data-bind=" +
"\"visible:$parent.edit.selectedTab.type()==\'form\'\"><select class=\"z-txt\"  data-bi" +
"nd=\"options:$root.data.input,value:type\"></select></td>\r\n                    <td" +
" data-bind=\"visible:$parent.edit.selectedTab.type()==\'form\'\"><input type=\"checkb" +
"ox\" data-bind=\"checked:readonly\"/></td>\r\n                </tr>\r\n            </tb" +
"ody>\r\n        </table>\r\n    </div>\r\n</script>\r\n ");

        }
    }
}
#pragma warning restore 1591
