#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zephyr.Web.Sys.Areas.Sys.Views.Generator
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Sys/Views/Generator/TemplateSearchEditController.cshtml")]
    public partial class TemplateSearchEditController : System.Web.Mvc.WebViewPage<dynamic>
    {
        public TemplateSearchEditController()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Areas\Sys\Views\Generator\TemplateSearchEditController.cshtml"
  
    var area = Model.Area;
    var condtions = Model.Data["conditions"];
    var columns = Model.Data["columns"];
    var controller = Model.Data["controller"];
    var count1 = condtions.Count;
    var count2 = columns.Count;
    var PrimaryKey = Model.PrimaryKeys[0];

            
            #line default
            #line hidden
WriteLiteral("\r\nusing System;\r\nusing System.Collections.Generic;\r\nusing System.Linq;\r\nusing Sys" +
"tem.Web;\r\nusing System.Web.Http;\r\nusing System.Web.Mvc;\r\nusing Zephyr.Core;\r\nusi" +
"ng Zephyr.Web.Sys.Models;\r\nusing Zephyr.Web.");

            
            #line 18 "..\..\Areas\Sys\Views\Generator\TemplateSearchEditController.cshtml"
             Write(area);

            
            #line default
            #line hidden
WriteLiteral(".Models;\r\n\r\nnamespace Zephyr.Web.");

            
            #line 20 "..\..\Areas\Sys\Views\Generator\TemplateSearchEditController.cshtml"
                 Write(area);

            
            #line default
            #line hidden
WriteLiteral(".Controllers\r\n{\r\n    public class ");

            
            #line 22 "..\..\Areas\Sys\Views\Generator\TemplateSearchEditController.cshtml"
             Write(controller);

            
            #line default
            #line hidden
WriteLiteral(@"Controller : Controller
    {
        public ActionResult Index()
        {
            var code = new sys_codeService();
            var model = new
            {
                dataSource = new{
                    dsPricing = code.GetValueTextListByType(""Pricing"")
                },
                urls = new{
                    query = ""/api/");

            
            #line 33 "..\..\Areas\Sys\Views\Generator\TemplateSearchEditController.cshtml"
                             Write(area);

            
            #line default
            #line hidden
WriteLiteral("/");

            
            #line 33 "..\..\Areas\Sys\Views\Generator\TemplateSearchEditController.cshtml"
                                   Write(controller);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n                    newkey = \"/api/");

            
            #line 34 "..\..\Areas\Sys\Views\Generator\TemplateSearchEditController.cshtml"
                              Write(area);

            
            #line default
            #line hidden
WriteLiteral("/");

            
            #line 34 "..\..\Areas\Sys\Views\Generator\TemplateSearchEditController.cshtml"
                                    Write(controller);

            
            #line default
            #line hidden
WriteLiteral("/getnewkey\",\r\n                    edit = \"/api/");

            
            #line 35 "..\..\Areas\Sys\Views\Generator\TemplateSearchEditController.cshtml"
                            Write(area);

            
            #line default
            #line hidden
WriteLiteral("/");

            
            #line 35 "..\..\Areas\Sys\Views\Generator\TemplateSearchEditController.cshtml"
                                  Write(controller);

            
            #line default
            #line hidden
WriteLiteral("/edit\" \r\n                },\r\n                resx = new{\r\n                    non" +
"eSelect = \"请先选择一条数据！\",\r\n                    editSuccess = \"保存成功！\",\r\n            " +
"        auditSuccess = \"单据已审核！\"\r\n                },\r\n                form = new{" +
"\r\n");

            
            #line 43 "..\..\Areas\Sys\Views\Generator\TemplateSearchEditController.cshtml"
                
            
            #line default
            #line hidden
            
            #line 43 "..\..\Areas\Sys\Views\Generator\TemplateSearchEditController.cshtml"
                 for (var i = 0; i < count1; i++)
                {

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral("    ");

            
            #line 45 "..\..\Areas\Sys\Views\Generator\TemplateSearchEditController.cshtml"
                 Write(condtions[i].field);

            
            #line default
            #line hidden
WriteLiteral(" = \"\" ");

            
            #line 45 "..\..\Areas\Sys\Views\Generator\TemplateSearchEditController.cshtml"
                                                if (i < count1 - 1) {
            
            #line default
            #line hidden
            
            #line 45 "..\..\Areas\Sys\Views\Generator\TemplateSearchEditController.cshtml"
                                                                 Write(",");

            
            #line default
            #line hidden
            
            #line 45 "..\..\Areas\Sys\Views\Generator\TemplateSearchEditController.cshtml"
                                                                           }
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 46 "..\..\Areas\Sys\Views\Generator\TemplateSearchEditController.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                },\r\n                defaultRow = new {\r\n                   \r\n    " +
"            },\r\n                setting = new{\r\n                    idField = \"");

            
            #line 52 "..\..\Areas\Sys\Views\Generator\TemplateSearchEditController.cshtml"
                          Write(PrimaryKey);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n                    postListFields = new string[] { ");

            
            #line 53 "..\..\Areas\Sys\Views\Generator\TemplateSearchEditController.cshtml"
                                                     for (var i = 0; i < count2; i++){
            
            #line default
            #line hidden
WriteLiteral("\"");

            
            #line 53 "..\..\Areas\Sys\Views\Generator\TemplateSearchEditController.cshtml"
                                                                                        Write(columns[i].field);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" ");

            
            #line 53 "..\..\Areas\Sys\Views\Generator\TemplateSearchEditController.cshtml"
                                                                                                                       if (i < count2 - 1){
            
            #line default
            #line hidden
            
            #line 53 "..\..\Areas\Sys\Views\Generator\TemplateSearchEditController.cshtml"
                                                                                                                                       Write(",");

            
            #line default
            #line hidden
            
            #line 53 "..\..\Areas\Sys\Views\Generator\TemplateSearchEditController.cshtml"
                                                                                                                                                 } }
            
            #line default
            #line hidden
WriteLiteral("}\r\n                }\r\n            };\r\n\r\n            return View(model);\r\n        " +
"}\r\n    }\r\n\r\n    public class ");

            
            #line 61 "..\..\Areas\Sys\Views\Generator\TemplateSearchEditController.cshtml"
             Write(controller);

            
            #line default
            #line hidden
WriteLiteral("ApiController : ApiController\r\n    {\r\n        public dynamic Get(RequestWrapper q" +
"uery)\r\n        {\r\n            query.SetXml(");

WriteLiteral("@\"\r\n<settings >\r\n    <select>*</select>\r\n    <from>");

            
            #line 68 "..\..\Areas\Sys\Views\Generator\TemplateSearchEditController.cshtml"
     Write(Model.TableName);

            
            #line default
            #line hidden
WriteLiteral("</from>\r\n    <where>\r\n");

            
            #line 70 "..\..\Areas\Sys\Views\Generator\TemplateSearchEditController.cshtml"
    
            
            #line default
            #line hidden
            
            #line 70 "..\..\Areas\Sys\Views\Generator\TemplateSearchEditController.cshtml"
     foreach(var item in condtions)
    {

            
            #line default
            #line hidden
WriteLiteral("        <c");

WriteAttribute("column", Tuple.Create(" column=\'", 2203), Tuple.Create("\'", 2223)
            
            #line 72 "..\..\Areas\Sys\Views\Generator\TemplateSearchEditController.cshtml"
, Tuple.Create(Tuple.Create("", 2212), Tuple.Create<System.Object, System.Int32>(item.field
            
            #line default
            #line hidden
, 2212), false)
);

            
            #line 72 "..\..\Areas\Sys\Views\Generator\TemplateSearchEditController.cshtml"
                          Write(Html.Raw("\t\t"));

            
            #line default
            #line hidden
WriteLiteral("symbol=\'");

            
            #line 72 "..\..\Areas\Sys\Views\Generator\TemplateSearchEditController.cshtml"
                                                   Write(item.cp);

            
            #line default
            #line hidden
WriteLiteral("\' ignore=\'empty\'></c>   \r\n");

            
            #line 73 "..\..\Areas\Sys\Views\Generator\TemplateSearchEditController.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    </where>\r\n    <orderby>");

            
            #line 75 "..\..\Areas\Sys\Views\Generator\TemplateSearchEditController.cshtml"
        Write(PrimaryKey);

            
            #line default
            #line hidden
WriteLiteral("</orderby>\r\n</settings>\");\r\n            var service = new ");

            
            #line 77 "..\..\Areas\Sys\Views\Generator\TemplateSearchEditController.cshtml"
                          Write(Model.TableName);

            
            #line default
            #line hidden
WriteLiteral("Service();\r\n            var pQuery = query.ToParamQuery();\r\n            var resul" +
"t = service.GetDynamicListWithPaging(pQuery);\r\n            return result;\r\n     " +
"   }\r\n\r\n        public string GetNewKey()\r\n        {\r\n            return new ");

            
            #line 85 "..\..\Areas\Sys\Views\Generator\TemplateSearchEditController.cshtml"
                   Write(Model.TableName);

            
            #line default
            #line hidden
WriteLiteral("Service().GetNewKey(\"");

            
            #line 85 "..\..\Areas\Sys\Views\Generator\TemplateSearchEditController.cshtml"
                                                         Write(PrimaryKey);

            
            #line default
            #line hidden
WriteLiteral("\", \"maxplus\").PadLeft(6, \'0\'); ;\r\n        }\r\n\r\n        [System.Web.Http.HttpPost]" +
"\r\n        public void Edit(dynamic data)\r\n        {\r\n            var tabsWrapper" +
" = RequestWrapper.InstanceArray(1);\r\n            tabsWrapper[0].SetXml(");

WriteLiteral("@\"\r\n<settings>\r\n    <table>");

            
            #line 94 "..\..\Areas\Sys\Views\Generator\TemplateSearchEditController.cshtml"
      Write(Model.TableName);

            
            #line default
            #line hidden
WriteLiteral("</table>\r\n    <where>\r\n        <c");

WriteAttribute("column", Tuple.Create(" column=\'", 3001), Tuple.Create("\'", 3021)
            
            #line 96 "..\..\Areas\Sys\Views\Generator\TemplateSearchEditController.cshtml"
, Tuple.Create(Tuple.Create("", 3010), Tuple.Create<System.Object, System.Int32>(PrimaryKey
            
            #line default
            #line hidden
, 3010), false)
);

WriteLiteral(" symbol=\'equal\'");

WriteLiteral("></c>\r\n    </where>\r\n</settings>\");\r\n            var service = new ");

            
            #line 99 "..\..\Areas\Sys\Views\Generator\TemplateSearchEditController.cshtml"
                          Write(Model.TableName);

            
            #line default
            #line hidden
WriteLiteral("Service();\r\n            var result = service.Edit(data,null, tabsWrapper);\r\n     " +
"   }\r\n    }\r\n}\r\n");

        }
    }
}
#pragma warning restore 1591
