#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zephyr.Web.Sys.Areas.Sys.Views.Generator
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\Sys\Views\Generator\TemplateCommonModel.cshtml"
    using Zephyr.Core.Generator;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Sys/Views/Generator/TemplateCommonModel.cshtml")]
    public partial class TemplateCommonModel : System.Web.Mvc.WebViewPage<dynamic>
    {
        public TemplateCommonModel()
        {
        }
        public override void Execute()
        {
WriteLiteral("using System;\r\nusing System.Collections.Generic;\r\nusing System.Text;\r\nusing Zephy" +
"r.Core;\r\n\r\nnamespace Zephyr.Web.");

            
            #line 7 "..\..\Areas\Sys\Views\Generator\TemplateCommonModel.cshtml"
                 Write(@Model.Area);

            
            #line default
            #line hidden
WriteLiteral(".Models\r\n{\r\n    [Module(\"");

            
            #line 9 "..\..\Areas\Sys\Views\Generator\TemplateCommonModel.cshtml"
        Write(Model.Database);

            
            #line default
            #line hidden
WriteLiteral("\")]\r\n    public class ");

            
            #line 10 "..\..\Areas\Sys\Views\Generator\TemplateCommonModel.cshtml"
             Write(Model.TableName);

            
            #line default
            #line hidden
WriteLiteral("Service : ServiceBase<");

            
            #line 10 "..\..\Areas\Sys\Views\Generator\TemplateCommonModel.cshtml"
                                                    Write(Model.TableName);

            
            #line default
            #line hidden
WriteLiteral(">\r\n    {\r\n       \r\n    }\r\n\r\n    public class ");

            
            #line 15 "..\..\Areas\Sys\Views\Generator\TemplateCommonModel.cshtml"
            Write(Model.TableName);

            
            #line default
            #line hidden
WriteLiteral(" : ModelBase\r\n    {\r\n");

            
            #line 17 "..\..\Areas\Sys\Views\Generator\TemplateCommonModel.cshtml"
 foreach(TableSchema item in Model.Columns)
{
    if (item.IsIdentity)
    {

            
            #line default
            #line hidden
WriteLiteral("        ");

WriteLiteral("[Identity]\r\n");

            
            #line 22 "..\..\Areas\Sys\Views\Generator\TemplateCommonModel.cshtml"
    }

    if (item.IsPrimaryKey)
    {

            
            #line default
            #line hidden
WriteLiteral("        ");

WriteLiteral("[PrimaryKey]   \r\n");

            
            #line 27 "..\..\Areas\Sys\Views\Generator\TemplateCommonModel.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("        ");

WriteLiteral("public ");

            
            #line 28 "..\..\Areas\Sys\Views\Generator\TemplateCommonModel.cshtml"
            Write(item.TypeName);

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 28 "..\..\Areas\Sys\Views\Generator\TemplateCommonModel.cshtml"
                           Write(item.ColumnName);

            
            #line default
            #line hidden
WriteLiteral(" { get; set; }\r\n");

            
            #line 29 "..\..\Areas\Sys\Views\Generator\TemplateCommonModel.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("    }\r\n}\r\n");

        }
    }
}
#pragma warning restore 1591
