#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zephyr.Web.Sys.Areas.Sys.Views.Log
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Sys/Views/Log/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Index()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Areas\Sys\Views\Log\Index.cshtml"
  
    ViewBag.Title = "title";
    Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n            var formatsys_log = function (value) {\r\n                var html =" +
" \'<a href=\"#\" onclick=\\\'view(\"\' + value + \'\")\\\'><span class=\"icon icon-search\">&" +
"nbsp;</span>[查看]</a>\';\r\n                html += \'<a href=\"/sys/log/download/\'+va" +
"lue+\'\" style=\"margin-left:10px\"><span class=\"icon icon-download\">&nbsp;</span>[下" +
"载]</a>\';\r\n                return html;\r\n            };\r\n\r\n            var viewMo" +
"del =function(){\r\n                var self = this;\r\n                this.form = " +
"{LogDate:ko.observable()};\r\n                this.login = {\r\n                    " +
"size: { w: 6, h: 123 },\r\n                    url: \"/api/sys/log/getloginlog\",\r\n " +
"                   queryParams: ko.observable(),\r\n                    pagination" +
": true\r\n                };\r\n                this.operate = {\r\n                  " +
"  size: { w: 6, h: 123 },\r\n                    url: \"/api/sys/log/getoperatelog\"" +
",\r\n                    queryParams: ko.observable(),\r\n                    pagina" +
"tion: true\r\n                };\r\n                this.system = {\r\n               " +
"     size: { w: 6, h: 123 },\r\n                    url: \"/api/sys/log/getsystemlo" +
"g\",\r\n                    queryParams: ko.observable(),\r\n                    pagi" +
"nation: true\r\n                };\r\n\r\n                this.refreshClick = function" +
" () {\r\n                    window.location.reload();\r\n                };\r\n\r\n    " +
"            this.searchClick = function () {\r\n                    this.login.que" +
"ryParams(ko.toJS(this.form));\r\n                    this.operate.queryParams(ko.t" +
"oJS(this.form));\r\n                    this.system.queryParams(ko.toJS(this.form)" +
");\r\n                };\r\n\r\n                this.clearClick = function () {\r\n     " +
"               this.form.LogDate(\"\");\r\n                    this.searchClick();\r\n" +
"                }\r\n            };\r\n\r\n            var view = function (id) {\r\n   " +
"             com.dialog({\r\n                    title: \"查看日志\",\r\n                 " +
"   width: 700,\r\n                    height: 500,\r\n                    maximizabl" +
"e: true,\r\n                    html: \'<iframe id=\"_view_sys_log_\" scrolling=\"auto" +
"\" frameborder=\"0\"  style=\"width:100%;height:100%;\"></iframe>\',\r\n                " +
"    viewModel: function (w) {\r\n                        w.find(\"iframe\").attr(\"sr" +
"c\", \"/sys/log/view/\" + id);\r\n                    }\r\n                });\r\n       " +
"     };\r\n\r\n            ko.bindingViewModel(new viewModel());\r\n        </script>\r" +
"\n");

});

WriteLiteral("        <div");

WriteLiteral(" class=\"z-toolbar\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" id=\"a_refresh\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" plain=\"true\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-arrow_refresh\"");

WriteLiteral(" title=\"刷新\"");

WriteLiteral(" data-bind=\"click:refreshClick\"");

WriteLiteral(">刷新</a>\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" id=\"condition\"");

WriteLiteral(" class=\"container_12\"");

WriteLiteral(" style=\"position:relative;height:50px;\"");

WriteLiteral(">\r\n             <div");

WriteLiteral(" class=\"clear\"");

WriteLiteral(" style=\"height:13px;\"");

WriteLiteral("></div>\r\n\r\n            <div");

WriteLiteral(" class=\"grid_1 lbl\"");

WriteLiteral(">日志日期</div>\r\n            <div");

WriteLiteral(" class=\"grid_2 val\"");

WriteLiteral("><input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" data-bind=\"value:form.LogDate\"");

WriteLiteral(" class=\"z-txt easyui-daterange\"");

WriteLiteral("/></div>\r\n \r\n            <div");

WriteLiteral(" class=\"prefix_9\"");

WriteLiteral(" style=\"position:absolute;top:5px;height:0;\"");

WriteLiteral(">  \r\n                <a");

WriteLiteral(" id=\"a_search\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"buttonHuge button-blue\"");

WriteLiteral(" style=\"margin:0 15px;\"");

WriteLiteral(" data-bind=\"click:searchClick\"");

WriteLiteral(">查询</a> \r\n                <a");

WriteLiteral(" id=\"a_reset\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"buttonHuge button-blue\"");

WriteLiteral(" data-bind=\"click:clearClick\"");

WriteLiteral(">清空</a>\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" id=\"tt\"");

WriteLiteral(" class=\"easyui-tabs\"");

WriteLiteral(">  \r\n            <div");

WriteLiteral(" title=\"登陆日志\"");

WriteLiteral(">\r\n                <table");

WriteLiteral(" data-bind=\"datagrid:login\"");

WriteLiteral(">\r\n                    <thead>  \r\n                        <tr>    \r\n             " +
"               <th");

WriteLiteral(" field=\"UserCode\"");

WriteLiteral("    align=\"left\"");

WriteLiteral("    width=\"70\"");

WriteLiteral(">登陆帐号   </th>  \r\n                            <th");

WriteLiteral(" field=\"UserName\"");

WriteLiteral("    align=\"left\"");

WriteLiteral("    width=\"100\"");

WriteLiteral(">用户名称   </th>  \r\n                            <th");

WriteLiteral(" field=\"HostIP\"");

WriteLiteral("      align=\"left\"");

WriteLiteral("    width=\"200\"");

WriteLiteral(" >登陆IP     </th> \r\n                            <th");

WriteLiteral(" field=\"HostName\"");

WriteLiteral("    align=\"left\"");

WriteLiteral("    width=\"100\"");

WriteLiteral(" >登陆机器名   </th>  \r\n                            <th");

WriteLiteral(" field=\"LoginCity\"");

WriteLiteral("   align=\"left\"");

WriteLiteral("    width=\"150\"");

WriteLiteral(" >登陆位置   </th>  \r\n                            <th");

WriteLiteral(" field=\"LoginDate\"");

WriteLiteral("   align=\"center\"");

WriteLiteral("  width=\"130\"");

WriteLiteral(" formatter=\"com.formatTime\"");

WriteLiteral(">登陆日期   </th>  \r\n                        </tr>                            \r\n     " +
"               </thead>      \r\n                </table>   \r\n            </div>\r\n" +
"\r\n            <div");

WriteLiteral(" title=\"操作日志\"");

WriteLiteral(">\r\n                 <table");

WriteLiteral(" data-bind=\"datagrid:operate\"");

WriteLiteral(">\r\n                    <thead>  \r\n                        <tr>    \r\n             " +
"               <th");

WriteLiteral(" field=\"UserCode\"");

WriteLiteral("    align=\"left\"");

WriteLiteral("    width=\"70\"");

WriteLiteral("  >操作帐号   </th>  \r\n                            <th");

WriteLiteral(" field=\"UserName\"");

WriteLiteral("    align=\"left\"");

WriteLiteral("    width=\"100\"");

WriteLiteral(" >操作人   </th>  \r\n                            <th");

WriteLiteral(" field=\"Position\"");

WriteLiteral("    align=\"left\"");

WriteLiteral("    width=\"150\"");

WriteLiteral(" >位置     </th> \r\n                            <th");

WriteLiteral(" field=\"Target\"");

WriteLiteral("      align=\"left\"");

WriteLiteral("    width=\"100\"");

WriteLiteral(" >对象   </th>  \r\n                            <th");

WriteLiteral(" field=\"Type\"");

WriteLiteral("        align=\"left\"");

WriteLiteral("    width=\"100\"");

WriteLiteral(" >类型   </th>  \r\n                            <th");

WriteLiteral(" field=\"Message\"");

WriteLiteral("     align=\"left\"");

WriteLiteral("    width=\"150\"");

WriteLiteral(" >数据   </th>  \r\n                            <th");

WriteLiteral(" field=\"Date\"");

WriteLiteral("        align=\"center\"");

WriteLiteral("  width=\"120\"");

WriteLiteral(" formatter=\"com.formatTime\"");

WriteLiteral(">日期   </th>  \r\n                        </tr>                            \r\n       " +
"             </thead>      \r\n                </table>\r\n            </div>\r\n     " +
"       <div");

WriteLiteral(" title=\"系统日志\"");

WriteLiteral(" >\r\n                <table");

WriteLiteral(" data-bind=\"datagrid:system\"");

WriteLiteral(">\r\n                    <thead>  \r\n                        <tr>    \r\n             " +
"               <th");

WriteLiteral(" field=\"filename\"");

WriteLiteral("    align=\"left\"");

WriteLiteral("    width=\"150\"");

WriteLiteral("  >日志文件   </th>  \r\n                            <th");

WriteLiteral(" field=\"size\"");

WriteLiteral("        align=\"left\"");

WriteLiteral("    width=\"100\"");

WriteLiteral(" >文件大小   </th>  \r\n                            <th");

WriteLiteral(" field=\"id\"");

WriteLiteral("    align=\"center\"");

WriteLiteral("    width=\"150\"");

WriteLiteral(" formatter=\"formatsys_log\"");

WriteLiteral(" >操作     </th> \r\n                        </tr>                            \r\n     " +
"               </thead>      \r\n                </table>     \r\n            </div>" +
" \r\n        </div> ");

        }
    }
}
#pragma warning restore 1591
