#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zephyr.Web.Sys.Areas.Sys.Views.Wizard
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Sys/Views/Wizard/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Index()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Areas\Sys\Views\Wizard\Index.cshtml"
  
    Layout = null;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<!DOCTYPE html>\r\n<html");

WriteLiteral(" xmlns=\"http://www.w3.org/1999/xhtml\"");

WriteLiteral(" dir=\'ltr\'");

WriteLiteral(">\r\n<head>\r\n\t<meta");

WriteLiteral(" http-equiv=\"Content-Type\"");

WriteLiteral(" content=\"text/html; charset=utf-8\"");

WriteLiteral(" />\r\n\t<title>数据库配置向导</title>\r\n\t<style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(">\r\n\t\thtml { background: #f9f9f9; }\r\n        body { background: #fff; color: #333;" +
" font-family: sans-serif; margin: 2em auto; padding: 1em 2em; -webkit-border-rad" +
"ius: 3px; border-radius: 3px; border: 1px solid #dfdfdf; max-width: 700px; }\r\n  " +
"      h1 { border-bottom: 1px solid #dadada; clear: both; color: #666; font: 24p" +
"x Georgia, \"Times New Roman\", Times, serif; margin: 30px 0 0 0; padding: 0; padd" +
"ing-bottom: 7px; }\r\n        #error-page { margin-top: 50px; }\r\n        #error-pa" +
"ge p { font-size: 14px; line-height: 1.5; margin: 25px 0 20px; }\r\n        #error" +
"-page code { font-family: Consolas, Monaco, monospace; }\r\n        ul li { margin" +
"-bottom: 10px; font-size: 14px; }\r\n        a { color: #21759B; text-decoration: " +
"none; }\r\n        a:hover { color: #D54E21; }\r\n        .button { display: inline-" +
"block; text-decoration: none; font-size: 14px; line-height: 23px; height: 24px; " +
"margin: 0; padding: 0 10px 1px; cursor: pointer; border-width: 1px; border-style" +
": solid; -webkit-border-radius: 3px; border-radius: 3px; white-space: nowrap; -w" +
"ebkit-box-sizing: border-box; -moz-box-sizing:    border-box; box-sizing:       " +
"  border-box; background: #f3f3f3; background-image: -webkit-gradient(linear, le" +
"ft top, left bottom, from(#fefefe), to(#f4f4f4)); background-image: -webkit-line" +
"ar-gradient(top, #fefefe, #f4f4f4); background-image:    -moz-linear-gradient(to" +
"p, #fefefe, #f4f4f4); background-image:      -o-linear-gradient(top, #fefefe, #f" +
"4f4f4); background-image:   linear-gradient(to bottom, #fefefe, #f4f4f4); border" +
"-color: #bbb; color: #333; text-shadow: 0 1px 0 #fff; }\r\n        .button.button-" +
"large { height: 29px; line-height: 28px; padding: 0 12px; }\r\n        .button:hov" +
"er,\r\n        .button:focus { background: #f3f3f3; background-image: -webkit-grad" +
"ient(linear, left top, left bottom, from(#fff), to(#f3f3f3)); background-image: " +
"-webkit-linear-gradient(top, #fff, #f3f3f3); background-image:    -moz-linear-gr" +
"adient(top, #fff, #f3f3f3); background-image:     -ms-linear-gradient(top, #fff," +
" #f3f3f3); background-image:      -o-linear-gradient(top, #fff, #f3f3f3); backgr" +
"ound-image:   linear-gradient(to bottom, #fff, #f3f3f3); border-color: #999; col" +
"or: #222; }\r\n        .button:focus  { -webkit-box-shadow: 1px 1px 1px rgba(0,0,0" +
",.2); box-shadow: 1px 1px 1px rgba(0,0,0,.2); }\r\n        .button:active { outlin" +
"e: none; background: #eee; background-image: -webkit-gradient(linear, left top, " +
"left bottom, from(#f4f4f4), to(#fefefe)); background-image: -webkit-linear-gradi" +
"ent(top, #f4f4f4, #fefefe); background-image:    -moz-linear-gradient(top, #f4f4" +
"f4, #fefefe); background-image:     -ms-linear-gradient(top, #f4f4f4, #fefefe); " +
"background-image:      -o-linear-gradient(top, #f4f4f4, #fefefe); background-ima" +
"ge:   linear-gradient(to bottom, #f4f4f4, #fefefe); border-color: #999; color: #" +
"333; text-shadow: 0 -1px 0 #fff; -webkit-box-shadow: inset 0 2px 5px -3px rgba( " +
"0, 0, 0, 0.5 ); box-shadow: inset 0 2px 5px -3px rgba( 0, 0, 0, 0.5 ); }\r\n      " +
"  .buttonArea{ text-align: right; }\r\n    </style>\r\n</head>\r\n<body");

WriteLiteral(" id=\"error-page\"");

WriteLiteral(">\r\n\t<p>在 <code>web.onfig</code> 中未找到权限系统数据库Sys的配置。纵云权限系统需要数据库支持才能正常运行。</p>\r\n    <" +
"p>需要帮助？ <a");

WriteLiteral(" href=\'http://www.zoewin.com/?page_id=338\'");

WriteLiteral(">联系我们</a></p>\r\n    <p>您可以用通过建库脚本或数据库备份手动创建该数据库，然后修改 <code>web.onfig</code> 文件中的数据" +
"库连接字符串，也可以通过我们提供的 web 向导来自动创建数据库、配置 <code>web.config</code> 文件。</p>\r\n    <p");

WriteLiteral(" class=\"buttonArea\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 3582), Tuple.Create("\"", 3607)
, Tuple.Create(Tuple.Create("", 3589), Tuple.Create<System.Object, System.Int32>(Href("~/sys/wizard/step1")
, 3589), false)
);

WriteLiteral(" class=\"button button-large\"");

WriteLiteral(">创建数据库</a></p>\r\n</body>\r\n</html>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
