#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zephyr.Web.Sys.Areas.Sys.Views.Wizard
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Sys/Views/Wizard/Step2.cshtml")]
    public partial class Step2 : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Step2()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Areas\Sys\Views\Wizard\Step2.cshtml"
  
    Layout = null;

            
            #line default
            #line hidden
WriteLiteral("\r\n<!DOCTYPE html>\r\n<html");

WriteLiteral(" xmlns=\"http://www.w3.org/1999/xhtml\"");

WriteLiteral(" dir=\'ltr\'");

WriteLiteral(">\r\n<head>\r\n\t<meta");

WriteLiteral(" http-equiv=\"Content-Type\"");

WriteLiteral(" content=\"text/html; charset=utf-8\"");

WriteLiteral(" />\r\n\t<title>");

            
            #line 8 "..\..\Areas\Sys\Views\Wizard\Step2.cshtml"
   Write(ViewData["Title"]);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n\t<style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(">\r\n\t\thtml { background: #f9f9f9; }\r\n\t\tbody { background: #fff; color: #333; font-" +
"family: sans-serif; margin: 2em auto; padding: 1em 2em; -webkit-border-radius: 3" +
"px; border-radius: 3px; border: 1px solid #dfdfdf; max-width: 700px; }\r\n\t\th1 { b" +
"order-bottom: 1px solid #dadada; clear: both; color: #666; font: 24px Georgia, \"" +
"Times New Roman\", Times, serif; margin: 30px 0 0 0; padding: 0; padding-bottom: " +
"7px; }\r\n\t\t#error-page { margin-top: 50px; }\r\n\t\t#error-page p { font-size: 14px; " +
"line-height: 1.5; margin: 25px 0 20px; }\r\n\t\t#error-page code { font-family: Cons" +
"olas, Monaco, monospace; }\r\n\t\tul li { margin-bottom: 10px; font-size: 14px; }\r\n\t" +
"\ta { color: #21759B; text-decoration: none; }\r\n\t\ta:hover { color: #D54E21; }\r\n\t\t" +
".button { display: inline-block; text-decoration: none; font-size: 14px; line-he" +
"ight: 23px; height: 24px; margin: 0; padding: 0 10px 1px; cursor: pointer; borde" +
"r-width: 1px; border-style: solid; -webkit-border-radius: 3px; border-radius: 3p" +
"x; white-space: nowrap; -webkit-box-sizing: border-box; -moz-box-sizing:    bord" +
"er-box; box-sizing:         border-box; background: #f3f3f3; background-image: -" +
"webkit-gradient(linear, left top, left bottom, from(#fefefe), to(#f4f4f4)); back" +
"ground-image: -webkit-linear-gradient(top, #fefefe, #f4f4f4); background-image: " +
"   -moz-linear-gradient(top, #fefefe, #f4f4f4); background-image:      -o-linear" +
"-gradient(top, #fefefe, #f4f4f4); background-image:   linear-gradient(to bottom," +
" #fefefe, #f4f4f4); border-color: #bbb; color: #333; text-shadow: 0 1px 0 #fff; " +
"}\r\n\t\t.button.button-large { height: 29px; line-height: 28px; padding: 0 12px; }\r" +
"\n\t\t.button:hover,\r\n\t\t.button:focus { background: #f3f3f3; background-image: -web" +
"kit-gradient(linear, left top, left bottom, from(#fff), to(#f3f3f3)); background" +
"-image: -webkit-linear-gradient(top, #fff, #f3f3f3); background-image:    -moz-l" +
"inear-gradient(top, #fff, #f3f3f3); background-image:     -ms-linear-gradient(to" +
"p, #fff, #f3f3f3); background-image:      -o-linear-gradient(top, #fff, #f3f3f3)" +
"; background-image:   linear-gradient(to bottom, #fff, #f3f3f3); border-color: #" +
"999; color: #222; }\r\n\t\t.button:focus  { -webkit-box-shadow: 1px 1px 1px rgba(0,0" +
",0,.2); box-shadow: 1px 1px 1px rgba(0,0,0,.2); }\r\n\t\t.button:active { outline: n" +
"one; background: #eee; background-image: -webkit-gradient(linear, left top, left" +
" bottom, from(#f4f4f4), to(#fefefe)); background-image: -webkit-linear-gradient(" +
"top, #f4f4f4, #fefefe); background-image:    -moz-linear-gradient(top, #f4f4f4, " +
"#fefefe); background-image:     -ms-linear-gradient(top, #f4f4f4, #fefefe); back" +
"ground-image:      -o-linear-gradient(top, #f4f4f4, #fefefe); background-image: " +
"  linear-gradient(to bottom, #f4f4f4, #fefefe); border-color: #999; color: #333;" +
" text-shadow: 0 -1px 0 #fff; -webkit-box-shadow: inset 0 2px 5px -3px rgba( 0, 0" +
", 0, 0.5 ); box-shadow: inset 0 2px 5px -3px rgba( 0, 0, 0, 0.5 ); }\r\n    </styl" +
"e>\r\n</head>\r\n<body");

WriteLiteral(" id=\"error-page\"");

WriteLiteral(">\r\n<p>\r\n    <h1>");

            
            #line 29 "..\..\Areas\Sys\Views\Wizard\Step2.cshtml"
   Write(ViewData["Title"]);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n    <p>");

            
            #line 30 "..\..\Areas\Sys\Views\Wizard\Step2.cshtml"
  Write(ViewData["Message"]);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 31 "..\..\Areas\Sys\Views\Wizard\Step2.cshtml"
    
            
            #line default
            #line hidden
            
            #line 31 "..\..\Areas\Sys\Views\Wizard\Step2.cshtml"
     if (ViewData["Status"] == "success")
    {

            
            #line default
            #line hidden
WriteLiteral("<ul>\r\n\t<li>您现在可以登录纵云权限系统了</li>\r\n\t<li>我们默认的用户名：admin 密码：1234</li>\r\n</ul>\r\n");

            
            #line 37 "..\..\Areas\Sys\Views\Wizard\Step2.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n\r\n<p");

WriteLiteral(" class=\"step\"");

WriteLiteral(" style=\"text-align:right;\"");

WriteLiteral(">\r\n");

            
            #line 41 "..\..\Areas\Sys\Views\Wizard\Step2.cshtml"
 if (ViewData["Status"] == "success")
{

            
            #line default
            #line hidden
WriteLiteral("    <a");

WriteLiteral(" href=\"/login\"");

WriteLiteral(" class=\"button button-large\"");

WriteLiteral(">现在登录</a>\r\n");

            
            #line 44 "..\..\Areas\Sys\Views\Wizard\Step2.cshtml"
}
else
{

            
            #line default
            #line hidden
WriteLiteral("    <a");

WriteLiteral(" href=\"javascript:history.go(-1);\"");

WriteLiteral(" class=\"button button-large\"");

WriteLiteral(">重试</a>\r\n");

            
            #line 48 "..\..\Areas\Sys\Views\Wizard\Step2.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("</p></body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
